### PR TITLE
QA eventsprocessor

### PR DESCRIPTION
**Pull request by joseph-flinn**
## Summary
Package the events processor in a docker container for the QA environment. 

Switched up how we are computing the lower cased service name in the matrix to follow the pattern in the QA deploy workflow.

### CODE REVIEW

**Review by vgrassia — COMMENTED** [review]
What's the reasoning behind adding a variable for the Docker repo?  Is it only because of the EventsProcessor image being in an ACR?

**Comment by joseph-flinn** [comment]
> What's the reasoning behind adding a variable for the Docker repo? Is it only because of the EventsProcessor image being in an ACR?

Yep. I thought it would be cleaner to add another matrix variable instead of adding an if/else check on the 8 tasks that use the ACR docker repo

**Comment by vgrassia** [comment]
> Yep. I thought it would be cleaner to add another matrix variable instead of adding an if/else check on the 8 tasks that use the ACR docker repo

That makes sense.  Why are we adding the QA EventsProcessor to master though?  Shouldn't we be using a prod EventsProcessor image under either the Bitwarden repo in Docker Hub, or a prod ACR?

**Comment by joseph-flinn** [comment]
This is currently just for the QA environment which really only needs the `rc` tag and I thought it would be good to include the `dev` tag for future testing on master. You do bring up a good point about Prod ACR. We should probably move the ACR to that subscription since the artifacts themselves are the final deployments (not a testing artifact)

**Review by vgrassia — APPROVED** [review]

**Pull request merged**
