### PR TITLE
Add ubisoft.com and ubi.com to equivialent domains list

### PR DESCRIPTION
**Pull request by setyb**
Set enum to 76 instead of 75 to allow room for existing pull request for oneprovider.com

### CODE REVIEW

**Comment by Lillecarl** [comment]
@kspearrin Any particular reason why this store is super hardcoded instead of loaded from file (JSON?)

**Comment by kspearrin** [comment]
@Lillecarl Not really. I do have a backlog item to work on converting this to a static JSON file fetched from the apps that can be hosted on our CDN since that does make more since.

**Comment by setyb** [comment]
@kspearrin If you go that route, don't forget to do some sort of  integrity check to limit the effectiveness of MITM attacks.  Erroneous equivalent domains can be a security issue.

Once in a while it will be a good idea to revalidate all equivalent domains as well.

**Comment by Lillecarl** [comment]
@setyb https should solve this, my thinking was honestly just adding a json to the build instead of hardcoding it.

If the json is distributed over HTTP I'd say it should be signed by a bitwarden cert though for that security indeed.

**Comment by eliykat** [comment]
Hi @setyb, I'm currently reviewing and cleaning up old pull requests. If you're still interested in progressing this PR, please:
* sign the Contributor License Agreement (see the link provided by the CLAassistant bot above)
* review/respond to any outstanding change requests or questions
* reply here and tag me (@) so that I can mark it for further review

As this PR is more than 12 months old, I'll close it for now. However, this is just housekeeping. We encourage our community members to get involved and make contributions, so you can comment here even after it's closed and I'll reopen it if required.

Thanks again for your submission!

**Pull request closed without merging**
