### PR TITLE
[PM-5551] Removing Autofill v2 and AutofillOverlay Feature Flags

### PR DESCRIPTION
**Pull request by cagonzalezcs**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This ticket removes the autofill v2 and autofill overlay feature flags to have these features be set by default. These changes also ensure that self-hosted Bitwarden servers have access to these features.

## Code changes

- **src/Core/Constants.cs:** Removing the AutofillV2 and AutofillOverlay feature flags

### CODE REVIEW

**Comment by cagonzalezcs** [comment]
Note to reviewers: These feature flags are obsolete now, as their usage within the extension has been removed entirely as of the `v2024.2.0` release. This PR just cleans up those flags entirely.

**Comment by withinfocus** [comment]
How long has this been out of the client code? We have to be sensitive to adoption, because if this releases server-side then a not-updated client will default to not getting the functionality. If that's an acceptable risk and timeline then we can merge.

**Comment by cagonzalezcs** [comment]
@withinfocus 

This change will be introduced with the upcoming release, `v2024.2.0`. The removal of this flag is present here - https://github.com/bitwarden/clients/pull/7642

I can definitely hold off on merging this work in after we introduce that version of the extension, if that makes sense to do. However, since `rc` was cut earlier this week, the changes in this PR should be release approximately 2 weeks after we release the client side removal.

**Comment by withinfocus** [comment]
I'd wait one more release cut to give the clients time to propagate.

**Comment by trmartin4** [comment]
> I'd wait one more release cut to give the clients time to propagate.

@withinfocus any concern with our 3-release backward compatibility on clients here?  Should we wait 3 client releases before we remove the flag altogether?  Or is it OK to go sooner since this is only in the browser and it's difficult (impossible?) to be running an old version in normal usage.

**Comment by withinfocus** [comment]
I think it's fine to go sooner, and the removal of flags isn't bound to the same compatibility rules as a feature itself e.g. a breaking change.

**Comment by cagonzalezcs** [comment]
@withinfocus @trmartin4 

Are we in a good position to merge this change in? Just looking to clear the Jira ticket for this task.

**Comment by withinfocus** [comment]
Especially since an RC just cut, yes I am in support.

**Comment by cagonzalezcs** [comment]
Fantastic thank you Matt! As soon as an approval is provided I'll make sure this gets merged in.

**Review by withinfocus — APPROVED** [review]
Please make sure your team is also approving if you feel that's warranted.

**Pull request merged**
