### PR TITLE
Increase self-signed certs duration

### LINKED ISSUE #507: Extend self-signed certificate life
Hi,
I just faced the situation where the self-signed certificate expired (installation behind a reverse proxy), leading to a service interruption.
This certificate has only 365 days of life :
https://github.com/bitwarden/server/blob/master/util/Setup/CertBuilder.cs
I think you could dramatically extend this by default (to 100 years for example), to avoid having to regenerate it.
Thank you !

### PR DESCRIPTION
**Pull request by Mart124**
Hi,

This PR closes #507, increasing self-signed certificates duration.

Many thanks 👍

### CODE REVIEW

**Comment by kspearrin** [comment]
According to http://openssl.6102.n7.nabble.com/Generating-Certificates-Maximum-Days-Value-td6987.html

> The *days* argument  in openssl will work  fine upto a Maximum value of
> *11499* in positive values.
> 
> If the days specified is beyond the value 11499, the parameter "Not After"
> date internally goes in negative. Thus on Certificate Verification, the
> certificate is considered as *Expired* 

Not sure if that is still true. Did you test this?

**Comment by Mart124** [comment]
Yes, I generated a test certificate with a 100 years duration.
Look, sounds good 👍

cert

**Comment by Mart124** [comment]
```
# openssl version
OpenSSL 1.1.0k  28 May 2019
```

**Comment by Mart124** [comment]
Thank you too :)

**Pull request merged**
