### PR TITLE
Add windowsazure.com to eq domains

### PR DESCRIPTION
**Pull request by Mart124**
Hi,

This PR adds `windowsazure.com` to Microsoft domains.

Thx 👍

### CODE REVIEW

**Comment by kspearrin** [comment]
Where is this used? When I log into the azure portal it is `azure.com`

**Comment by Mart124** [comment]
You can also login from here :
https://account.activedirectory.windowsazure.com/

**Comment by kspearrin** [comment]
Can you add `azure.com` as well?

**Comment by Mart124** [comment]
Sure, just done!

**Comment by Mart124** [comment]
Thank you Kyle :+1:

**Pull request merged**
