### PR TITLE
[AC-1985] Fix collection permissions when editing items

### PR DESCRIPTION
**Pull request by eliykat**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

We fixed `UserCipherDetails_V2` in https://github.com/bitwarden/server/pull/3491, but didn't refresh the metadata on the sprocs that call it. This means that the defect is still occurring.

## Code changes

Add a migration to refresh each sproc that calls `UserCipherDetails_V2`.

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Review by rkac-bw — APPROVED** [review]
looks good to me

**Comment by eliykat** [comment]
This fix still wasn't working. I've posted about it in `team-eng-dbops`, but in the meantime I've tried repeating the earlier migration in full (but with the fix) to see if that'll work (rather than just refreshing metadata).

**Comment by eliykat** [comment]
QA advised that the latest changes have resolved the issue, we should be good to go now.

**Review by rkac-bw — APPROVED** [review]
looks good to me

**Pull request merged**
