### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by GieltjE**
This fixes a lot of warnings in the log files and in some cases a problem where you cannot login untill you restart the API after mssql has been started properly.

### CODE REVIEW

**Comment by Mart124** [comment]
> you cannot login untill you restart the API after mssql has been started properly

Strange, my `mssql` (and only `mssql`) container is restarted every night as part of my backup strategy, and never faced this.
On several instances.

Anyway, for the same reason, `mssql` restarted periodically, I'm not so inclined to see this PR merged, as it would then impact other containers... That's my own opinion :) Thx 👍

**Comment by GieltjE** [comment]
Getting a lot of the following exception because mssql is much slower then the rest to start, reboot my server often enough and it never seemed to be a problem until once today, after another reboot everything was ok.
If we can mitigate these errors an potential follow up problems it would seem beneficial to merge it.

```
2021-01-07 10:15:25.877 +00:00 [Error] A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)
```

**Comment by cscharf** [comment]
@joseph-flinn , can you please take a look, not quite sure this is needed but worth a review.

**Comment by GieltjE** [comment]
Feel free to fix any missing/wrong dependencies, I just figured these out by mssql errors in the various logs.

**Comment by joseph-flinn** [comment]
@GieltjE It looks like Docker Compose dropped support for the `depends_on.<svc>.condition` in file specification [version 3](https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on). We are currently using version 3 for our self-host option, and while this fix doesn't necessarily break the current docker-compose.yml (I have tested it), there are [reports](https://forums.docker.com/t/depends-on-version-3/29463) from the docker community that using `depends_on.<svc>.condition` may be a breakable change. I am hesitant to make a change that is not supported by version 3.

**Comment by GieltjE** [comment]
@joseph-flinn Still having these issues, could we try something like https://github.com/bitwarden/server/pull/1075/commits/9069a72e3704aa5e420a1f4ee33349162931b319?

**Pull request closed without merging**
