### PR TITLE
[AC-108] Enterprise policies are not removed when downgraded to teams

### PR DESCRIPTION
**Pull request by r-tome**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
If an organization has `UsePolicies = false` then any of its members should not be affected by any previously configured policy.

## Code changes

Part of the solution was implemented on https://github.com/bitwarden/server/pull/2917 to select organization features for te selected plan. I've built further on that by setting the features for the Free and Families plans.

* **src/Admin/Views/Organizations/Edit.cshtml:** Setting `trial = true` when clicking trial buttons
* **src/Admin/Views/Shared/_OrganizationFormScripts.cshtml:** Using new parameter `trial` to set value for `SalesAssistedTrialStarted`. Added plans 'free' and 'families' to switch to toggle features
* **src/Infrastructure.EntityFramework/Repositories/OrganizationUserRepository.cs:** Filtering by organizations that have `UsePolicies = true`
* **src/Sql/dbo/Stored Procedures/OrganizationUser_ReadByUserIdWithPolicyDetails.sql:** Filtering by organizations that have `UsePolicies = true`
* **util/Migrator/DbScripts/2023-06-13_00_OrgUserPolicyDetailsAddFilterOrgUsePolicies.sql:** SQL migration file

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Review by eliykat — COMMENTED** [review]
This db query is already resource intensive (see PM-3007). I think we should address those concerns before fixing this bug, given that it introduces an additional table join. I'll add it as blocking in Jira.

**Review by eliykat — COMMENTED** [review]
A few notes, I'll review the rest once you've merged in `master` to clean up the diff.

**Comment by r-tome** [comment]
@eliykat I experimented with using `IApplicationCacheService` to get the `OrganizationAbilities` to the determine if a given `OrganizationId` has `UsePolicies` enabled. This is what the query method on `PolicyService` looked like:
```
private async Task<IEnumerable<OrganizationUserPolicyDetails>> QueryOrganizationUserPolicyDetailsAsync(Guid userId, PolicyType? policyType, OrganizationUserStatusType minStatus = OrganizationUserStatusType.Accepted)
    {
        // Check if the cached policies are available
        if (_cachedOrganizationUserPolicyDetails == null)
        {
            // Cached policies not available, retrieve from the repository
            _cachedOrganizationUserPolicyDetails = await _organizationUserRepository.GetByUserIdWithPolicyDetailsAsync(userId);
        }

        var excludedUserTypes = GetUserTypesExcludedFromPolicy(policyType);
        var orgAbilities = await _applicationCacheService.GetOrganizationAbilitiesAsync();
        return _cachedOrganizationUserPolicyDetails.Where(o =>
            (!orgAbilities.ContainsKey(o.OrganizationId) || orgAbilities[o.OrganizationId].Enabled && orgAbilities[o.OrganizationId].UsePolicies) &&
            (policyType == null || o.PolicyType == policyType) &&
            o.PolicyEnabled &&
            !excludedUserTypes.Contains(o.OrganizationUserType) &&
            o.OrganizationUserStatus >= minStatus &&
            !o.IsProvider);
    }
```

This worked perfectly until I also ran the Admin Panel alongside it and changed the `UsePolicies` value but then the cached value was not updated ([even though we do update the organization abilities](https://github.com/bitwarden/server/blob/a5bda60c4e4336619f29b00d3a2ac5bc8ef5c2fd/src/Admin/Controllers/OrganizationsController.cs#L203)). Could this be an issue on my development environment?

**Comment by eliykat** [comment]
If the org abilities cache is in memory only, it wouldn't be shared between the projects. Did you find out whether it's in memory in prod, or is it hosted on a service like redis etc? (Or otherwise shared between the projects somehow?)

**Comment by r-tome** [comment]
@eliykat I've created [another PR](https://github.com/bitwarden/server/pull/3168) with the changes above implemented and tested it by using a service bus resource on Azure. It worked great!

**Comment by eliykat** [comment]
@r-tome just a reminder to close this one if it's no longer needed.

**Pull request closed without merging**
