### PR TITLE
Various updates to global equivalent domains

### PR DESCRIPTION
**Pull request by jjlin**
See individual commit messages for rationale.

Closes #455
Closes #461
Closes #1063

### CODE REVIEW

**Comment by cscharf** [comment]
Do these equivalents you have based on parent company/ownership _share_ the exact same login information across them all?

**Comment by jjlin** [comment]
For Disney, it seems so. For example, I have an existing account at marvel.com. Attempting to create an account at abc.com, freeform.com, espn.com, fxnetworks.com, d23.com, or shopdisney.com results in a message like

> It looks like that email has already been used to create an account at Disney, ESPN, Marvel, or ABC. If this is your email address, just sign in to your account.

Filling in your login email at nationalgeographic.com produces the message

> Enter the password you use for Disney, ABC, ESPN, FX, or Nat Geo TV.

I don't use any Alibaba sites, but I made an account at aliexpress.com, and it doesn't seem to work for alibaba.com, aliyun.com, or net.cn. My aliexpress.com login also doesn't work on taobao.com. So it looks like the existing Alibaba entries in Bitwarden aren't accurate, but I'll just remove my changes and leave it for someone who cares about the Alibaba sites to sort it out.

**Comment by jjlin** [comment]
Any other concerns with these changes?

**Comment by cscharf** [comment]
I did not have any right now, no, however I haven't had the time to do a full review. Will take a look at these after our upcoming release and the team should have some bandwidth. Unless anyone from the community can jump in and ratify + 👍🏻

**Comment by jjlin** [comment]
Closing for lack of review interest

**Pull request closed without merging**
