### PR TITLE
Update bitwarden.sh

### PR DESCRIPTION
**Pull request by Jerome2103**
Change Version

### CODE REVIEW

**Comment by cscharf** [comment]
These do not get changed for a day or 2 after a new release so we can work out any issues in production before it gets released "in the wild" and becomes really, really hard to update/fix.

**Review by cscharf — CHANGES_REQUESTED** [review]
HOLD

**Review by Jerome2103 — COMMENTED** [review]
fixed

**Comment by Flol0** [comment]
When will this be changed?

**Comment by cscharf** [comment]
> When will this be changed?

We are evaluating any/all issues submitted since our release and over the weekend from GitHub and our customer success team to ensure we don't need any patches/hotfixes. We are scheduled to merge these in today if all goes well.

**Review by cscharf — APPROVED** [review]

**Comment by lgwapnitsky** [comment]
I'm on master and just did a pull, but don't see this. HOw can I get this file and update my BW to the latest version?

**Comment by cscharf** [comment]
> I'm on master and just did a pull, but don't see this. HOw can I get this file and update my BW to the latest version?

Are you running locally from source, building your containers manually from source or using the "easy" self-hosted setup scripts? Generally you wouldn't pull this down but simply run `./bitwarden.sh updateself` or `./bitwarden.sh update`. If you want to run off of the latest in `master` you would change the 2 version strings in your `bitwarden.sh` file to `dev`.

**Comment by lgwapnitsky** [comment]
I pulled from git, did a file search, and don't have the file. Should I
export and rebuild?

**Comment by cscharf** [comment]
> I pulled from git, did a file search, and don't have the file. Should I export and rebuild?

Are you trying to do local development or just run Bitwarden as a self-hosted instance? If just self-hosted, please see [this help article](https://bitwarden.com/help/article/install-on-premise/) on getting it setup

**Comment by lgwapnitsky** [comment]
I"m not running it on docker. I followed the instructions from here  -https://github.com/dani-garcia/bitwarden_rs - guess it's not standard, as I didn't want to use docker in my container.  I'll contact them and see if I can get an answer

**Comment by lgwapnitsky** [comment]
My installation was actually based on this. Guess I'll have to redo and use
docker to get the latest and greatest

**Pull request merged**
