### PR TITLE
[SM-82] Add HttpController Attribute to protect secrets manager controllers during development

### PR DESCRIPTION
**Pull request by Thomas-Avery**
## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The purpose of this PR is to create an attribute that can be used as a decorator for secrets manager controllers/methods that prevents code execution in non-developer environments. 

## Code changes

src/Api/Utilities/SecretsManagerAttribute.cs

The attribute class that prevents execution in non developer environments. 

When `!env.IsDevelopment()` HTTP status code 404 "Not Found" will be returned to the caller.

## Usage Examples

The attribute is intended to be used in two different ways.

On an entire controller:
### Example code
```
using Bit.Api.Utilities;
using Microsoft.AspNetCore.Mvc;

namespace Bit.Api.Controllers
{
    [ApiController]
    [Route("secrets")]
    [SecretsManager]
    public class SecretsController
    {
        [HttpGet(Name = "GetSecret")]
        public ActionResult<string> Get()
        {
            return "Secret";
        }
    }
}
```

Or on an individual method:
### Example code
```
using Bit.Api.Utilities;
using Microsoft.AspNetCore.Mvc;

namespace Bit.Api.Controllers
{
    [ApiController]
    [Route("secrets")]
    public class SecretsController
    {
        [HttpGet(Name = "GetSecret")]
        [SecretsManager]
        public ActionResult<string> Get()
        {
            return "Secret";
        }
    }
}
```

## Before you submit

```
- [X] I have checked for formatting errors (`dotnet format --verify-no-changes`) (required)
- [ ] If making database changes - I have also updated Entity Framework queries and/or migrations
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)
```

### CODE REVIEW

**Comment by Hinton** [comment]
While `DevelopmentOnly` accurately describes the functionality of this attribute it locks us into that behavior. I feel that calling it `SecretsManager` or something similar would work better as we most likely want to move away from the development check once we figure out a better method.

**Comment by Thomas-Avery** [comment]
@Hinton  name updated and PR examples updated to new name.

**Comment by Hinton** [comment]
Linting is failed, looks good otherwise.

**Comment by Thomas-Avery** [comment]
@Hinton  Yes, that is an issue from the master branch when I created this branch. Once merged, there will be no linting errors.

**Pull request merged**
