### PR TITLE
Replace `async void` with `async Task`

### PR DESCRIPTION
**Pull request by justindbaur**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

`async void` tests are treated as fire and forget. Since test failures are done through exceptions this could have or is masking some test failures.

## Code changes

Find and replace for `async void` -> `async Task`

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Review by Thomas-Avery — APPROVED** [review]
SM changes look good, thank you.

**Review by shane-melton — APPROVED** [review]
Vault changes look good!

**Review by cyprain-okeke — APPROVED** [review]
Looks Good

**Review by vincentsalucci — APPROVED** [review]
Admin console files look good!

**Pull request merged**
