### PR TITLE
PM-2944] Make Entities Nullable In Admin Console

### PR DESCRIPTION
**Pull request by justindbaur**
## 📔 Objective

Enable [nullable reference types feature](https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references) on core Admin Console entities. This is a foundational step towards enabling it project wide and an ensuring we have accurate request/response models.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Review by eliykat — COMMENTED** [review]
Can you provide any more info or documentation on the approach here? Best I can tell:
* if a property is nullable in the database, it's made nullable (`?`)
* if a property isn't nullable in the database and isn't initialized, it's forcibly assigned a null value (`= null!`). (Isn't this misleading when turning on `#nullable` though?)
* if a property isn't nullable in the database and is initialized, no change

Is that right?

Either way I'm keen to understand more about the overall strategy. I definitely support the effort.

**Comment by justindbaur** [comment]
@eliykat 

1. If it's a `(N)VARCHAR` in the database and marked as `NULL` then it gets a new `?` all the value types stored in the database that can be null already have `?` on them (at least for the most part, the last time I remember looking at this I saw some errors there).

2. Yes, the `= null!` is all so we can use the `!` [null-forgiving operator](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving). It's kind of misleading but I prefer to call it "overriding the compiler" lol. It's because it can't really analyze that this type is mostly created through reflection. We can also make the property [`required`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/required) and then it forces you to create it. I did actually try this on organization but unfortunately it causes a lot of errors in tests. If teams wanted to go through and mark them required then I am all for that but it felt out of scope here.

3. Exactly

**Review by eliykat — APPROVED** [review]
Thank you!

**Review by eliykat — DISMISSED** [review]

**Review by rkac-bw — APPROVED** [review]
lgtm

**Review by eliykat — APPROVED** [review]

**Review by rkac-bw — APPROVED** [review]
LGTM

**Pull request merged**
