### PR TITLE
Properly download bitwarden.sh

### LINKED ISSUE #705: update procedure breaks bitwarden.sh if Github servers don't respond as expected
I have a simple cron job that executes `bitwarden.sh updateself` and `bitwarden.sh update` every two hours, to keem the system up to date.
After it ran the last time, my `bitwarden.sh` was broken - it only contained this line:
```
500: Internal Server Error
```

Fixing it was quite simple (just downloaded the current version with `wget -qObitwarden.sh https://raw.githubusercontent.com/bitwarden/server/master/scripts/bitwarden.sh`), but I stronlgy recommend changing the update process to something like:

1. download the new file with a temporary file name
2. verify the file's consistency (i.e. by comparing it's sha256 hash)
3. actually replace the old file with the downloaded file

### PR DESCRIPTION
**Pull request by Mart124**
Hi,

This closes #705.
I'm not so pleased with `.ps1` scripts, so feel free to propose something similar for Windows.

Thx :+1:

### CODE REVIEW

**Comment by Mart124** [comment]
Mmmh I just saw the other proposal in #709.
This PR is much simpler.
Not sure we need all the checksum stuff.
`curl` will refuse to download the file (and thus will return something different then `HTTP 20X`) if github.com HTTPS certificate is not valid.
An attacker would then have to compromise the host itself to add its own certificate to `curl` CA store. And at this time then, host is already compromised...

**Comment by kspearrin** [comment]
@Mart124 The issue the contributor in #709 was trying to solve was when GitHub was having some downtime and the resulting downloaded file containing a 500 error message string instead of our real content. Is that handled by your PR?

**Comment by Mart124** [comment]
At this failure time, if GitHub returns a HTTP code other than `20X`, then yes.
I think we can expect GitHub not to return `HTTP 200` when it throws `Internal Server Error` :)

**Comment by Mart124** [comment]
I allowed `HTTP 20X`, but I think we could even restrict to `HTTP 200` only. Up to you :)

**Comment by kspearrin** [comment]
Is there not a simple PowerShell solution that is similar?

**Comment by Mart124** [comment]
Let's have a look yes.

**Comment by Mart124** [comment]
According to the `Invoke-RestMethod` manual :
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod
And especially to its `-SkipHttpErrorCheck` option description, I would say that without this option, requests throwing results other than `HTTP 20X` are not proceeded.
So should already be OK.

A simple test could be perform against a test URL returning `HTTP 200` and then returning `HTTP 500` (for example).

**Comment by kspearrin** [comment]
Thanks @Mart124

**Pull request merged**
