### PR TITLE
Added transferwise equivalent domains

### PR DESCRIPTION
**Pull request by haneef95**
TransferWise.com and Wise.com

## Type of change
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Code changes

* **file.ext:** Description of what was changed and why

## Before you submit
- [ ] If making database changes - I have also updated Entity Framework queries and/or migrations
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Review by Hinton — DISMISSED** [review]
I think this one looks good. @cscharf can you confirm?

**Comment by cscharf** [comment]
> I think this one looks good. @cscharf can you confirm?

Confirmed, looks good.

**Comment by djsmith85** [comment]
@haneef95 Sorry for the merge conflicts. I merged a equivalent domain PR 2 days ago. Could you please resolve them and we'll get this merged.

**Comment by haneef95** [comment]
I had that considered when making this PR, hence the different ID.

Is this something you could resolve? I'm currently not near my machine atm, sorry.

**Comment by djsmith85** [comment]
> I had that considered when making this PR, hence the different ID.
> 
> Is this something you could resolve? I'm currently not near my machine atm, sorry.

No worries, it is a sunday and your free time. Resolved conflicts.

**Review by djsmith85 — APPROVED** [review]

**Comment by haneef95** [comment]
Thanks

Enjoy your weekend! 😊

**Pull request merged**
