### PR TITLE
Update File Size to allow null

### PR DESCRIPTION
**Pull request by justindbaur**
## Type of change
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Asana Ticket: https://app.asana.com/0/0/1201753604759430/f

Mobile sends over the file object with all `null` values. This is different from web which doesn't send over that property so Json was reading it as the default of `long` zero.  Making it a nullable `long` means mobile continues to work as before and it reflects the true value of what web sends `null`.

This will be 🍒⛏️ to `rc`.

## Code changes

* **SendFileModel.cs:** Made Size property nullable
* **SendService.cs:** Default to zero when Size value is needed as a non-nullable number

## Testing requirements

- Verify that you are able to create/edit/save Sends in:
  - web
  - mobile
  - desktop
  - browser
  - cli
- Verify that file sends count against user storage limits.
- Verify that a bad actor cannot grab the blob storage link and upload a file larger than the users storage allows. i.e they only have 1GB of storage but upload 2GB file.

## Before you submit
- [x] I have checked for formatting errors (`dotnet tool run dotnet-format --check`) (required)
- [ ] If making database changes - I have also updated Entity Framework queries and/or migrations
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Review by differsthecat — DISMISSED** [review]

**Review by MGibson1 — COMMENTED** [review]
This feels like solving the problem on the wrong side.

Why are the clients not telling us the size of file to expect?

**Comment by justindbaur** [comment]
> This feels like solving the problem on the wrong side.
> 
> Why are the clients not telling us the size of file to expect?

It more has to do with the models. I believe we are being lazy with the models we are using and are reusing them. So for the request body we use this type in it even though most parts are not needed. 

There is also a problem with backwards compatibility of the app. Without this, we need to change the model which is probably a bit larger or change it on the app but anyone who takes a little time to update their app would have issues. I think this change has to go in no matter what but we also need to look into how we are making the body for this call on each client.

**Comment by MGibson1** [comment]
What endpoint is causing the error?

**Review by MGibson1 — APPROVED** [review]
Glad this got reduced down to this one model. I feel much better about this, thanks!

**Pull request merged**
