### PR TITLE
[PM-4589] Fix 2023-09-11_01_2023-02-FutureMigration

### PR DESCRIPTION
**Pull request by Hinton**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

The type needs to be dropped after the procedures that uses it.

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Review by fedemkr — APPROVED** [review]
LGTM 🚀

**Comment by Hinton** [comment]
It seems `OrganizationUserType` is used by `OrganizationUser_ReadByUserIdWithPolicyDetails`

**Review by eliykat — APPROVED** [review]
Thanks for handling!

**Comment by eliykat** [comment]
Merging at QA's request so that we can pick to `rc` for testing.

Removing the `db-migrations-changed` label because this is a valid case where we had to fix up a previous script.

**Pull request merged**
