### PR TITLE
[AC-1287] AC Team code ownership moves: Policies (1/2)

### PR DESCRIPTION
**Pull request by eliykat**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Move policies into AC Team code ownership.

## Code changes

* **file.ext:** Description of what was changed and why

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Review by andrebispo5 — APPROVED** [review]
LGTM

**Review by MGibson1 — CHANGES_REQUESTED** [review]
You have a delete/add in this ownership move PR. Please follow the [recommendations](https://bitwarden.atlassian.net/wiki/spaces/DEV/pages/373948418/Pod+-+Team+Code+Reorganization+Plan#%5BinlineExtension%5DOnly-File-Renames-in-Commits) to handle bad git move detections.

**Comment by eliykat** [comment]
@MGibson1 your feedback should be addressed. Changes have been reorganized into 2 commits so that the problematic files were moved and then updated separately. The history is also tidy enough that it can be merged into `master` without squashing which should maintain this history.

**Comment by eliykat** [comment]
The second commit will be in a separate PR so that I don't have to try to get repository settings tweaked.

**Review by MGibson1 — APPROVED** [review]
Only using and namespace changes and all moves correctly detected as moves :shipit:

**Review by Jingo88 — APPROVED** [review]

**Review by jlf0dev — APPROVED** [review]

**Review by vincentsalucci — APPROVED** [review]

**Review by audrey-jensen — APPROVED** [review]
LGTM!

**Pull request merged**
