### PR TITLE
Dynamic naming and versioning of containers during deployment

### PR DESCRIPTION
**Pull request by haneef95**
## Type of change
- [x] New feature development
- [x] Build/deploy pipeline (DevOps)
- [ ] Bug fix
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Other

## Objective

Follow up from an earlier pull request #1727 to complete this [feature request](https://community.bitwarden.com/t/appropriate-naming-of-bitwarden-docker-networks-and-containers/35341/2) (now Github contrinution).

## Code changes

1. The `export` in `run.sh` will allow `docker-compose` to access the variables at runtime, as they're referenced in `docker-compose.yml`
2. Check #1727 to elaborate on L116 - L119 of `run.sh` below.
3. `${COMPOSE_PROJECT_NAME:-bitwarden}` instructs `docker-compose` to use the value of `COMPOSE_PROJECT_NAME` variable, otherwise, it defaults to 'bitwarden'.

This is helpful to easily create staging environments, the [feature request](https://community.bitwarden.com/t/appropriate-naming-of-bitwarden-docker-networks-and-containers/35341/2) (now Github contribution) shows an example:
image

* **file.ext:** Description of what was changed and why

## Testing requirements

Bitwarden seems to be using the service names for inter-container networking, example below:
https://github.com/bitwarden/server/blob/d3673cdc8513a0846694ae0aff6b205f42838c73/util/Setup/Templates/NginxConfig.hbs#L117-L131

Hence, this PR shouldn't affect that, as it only changes the `container_name`.

## Before you submit
- [ ] If making database changes - I have also updated Entity Framework queries and/or migrations
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [x] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Comment by haneef95** [comment]
Follow up from: [Appropriate naming of bitwarden docker networks and containers](https://community.bitwarden.com/t/appropriate-naming-of-bitwarden-docker-networks-and-containers/35341/3)

**Comment by haneef95** [comment]
Hey,

Any chance this could be reviewed and released for the upcoming release?

Would really help with my setup. =)

Thanks,

**Comment by Hinton** [comment]
I'm struggling to see the benefit of prefixing the container names, however I do agree that we should have set a proper `COMPOSE_PROJECT_NAME` in  `.env`. Which I believe would solve the initial issue. FYI, you can also set the environment variable yourself in your terminal session.

As to version, not everyone uses the `bitwarden.sh` script, and the current approach of setting the versions in `docker-compose.yml` allows for running it directly. 

@vgrassia you commented on the initial PR, any other thoughts?

**Comment by haneef95** [comment]
> I'm struggling to see the benefit of prefixing the container names
@Hinton 

The prefix `bitwarden` already exists anyway, example:
https://github.com/bitwarden/server/blob/d3673cdc8513a0846694ae0aff6b205f42838c73/util/Setup/Templates/DockerCompose.hbs#L21

In relation to that line, this PR only gives the users option to change that prefix (example: `bwprod`, `bwstaging`, `bwdedicatedcust1` and etc) as per their need, otherwise, it defaults to `bitwarden` (as it currently exists).
https://github.com/bitwarden/server/blob/54a6e20dee79edecf1935fb31c535d150bb5228f/util/Setup/Templates/DockerCompose.hbs#L21

The default `bitwarden` is used if `COMPOSE_PROJECT_NAME` variable doesn't exist in the environment.

**Comment by haneef95** [comment]
> Changing it now would require a bit of research to ensure compatability with existing setups though
@Hinton 

True, based on my quick checks, all the containers seem to be communicating with each other using the `service name` as opposed to the `container_name`, example:
https://github.com/bitwarden/server/blob/d3673cdc8513a0846694ae0aff6b205f42838c73/util/Setup/Templates/DockerCompose.hbs#L37

https://github.com/bitwarden/server/blob/d3673cdc8513a0846694ae0aff6b205f42838c73/util/Setup/Templates/NginxConfig.hbs#L62

No issues with different container names in my test either.

____

> FYI, you can also set the environment variable yourself in your terminal session.

True, however, it only reflects on the network name, not the containers, as `container_name` is 'hard-coded' in the yml.

____

> the current approach of setting the versions in `docker-compose.yml` allows for running it directly using docker-compose

We can still maintain that feature by defining `COREVERSION` and `WEBVERSION` in the `.env` file in same folder as `docker-compose.yml`, according to official docs:

> Compose supports declaring default environment variables in an environment file named .env placed in the project directory.
https://docs.docker.com/compose/env-file/

____

Hope this clarifies all your queries.

**Comment by Hinton** [comment]
I think that feels more like we should strive towards removing `container_name`. And let it be dynamically set from `COMPOSE_PROJECT_NAME`. @joseph-flinn you are more familiar with the deployment stuff, any thoughts?

**Comment by joseph-flinn** [comment]
I like the direction that this is heading. I think that there needs to be more flexibility in the self-host release, but unfortunately DevOps does not have the capacity to conduct the needed regression testing at this time.

**Pull request closed without merging**
