### PR TITLE
[AC-1468] Exclude Secrets Manager beta users from seat and service account limits

### PR DESCRIPTION
**Pull request by r-tome**
## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Exclude beta users from seat and service account limits.

## Code changes
- **bitwarden_license/src/Commercial.Core/SecretsManager/Queries/ServiceAccounts/CountNewServiceAccountSlotsRequiredQuery.cs:** If organization participated in Secrets Manager Beta then no new service accounts are needed
- **bitwarden_license/test/Commercial.Core.Test/SecretsManager/Queries/ServiceAccounts/CountNewServiceAccountSlotsRequiredQueryTests.cs:** Updated tests to set value for SecretsManagerBeta and added new test

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by eliykat** [comment]
This is service accounts only for now, seats are waiting on https://github.com/bitwarden/server/pull/3121, but that'll be an identical change.

**Review by Thomas-Avery — APPROVED** [review]
Looks good, thank you!

**Comment by eliykat** [comment]
@r-tome I suggest you merge this without the seat changes, given that I've handled seats in #3121. Then just mark the ticket as blocked until #3121 is merged.

**Comment by vvolkgang** [comment]
The issues identified by Checkmarx aren't related to this PR, merging it.

**Pull request merged**
