### PR TITLE
[AC-1104] [AC-1265] Allow custom users with import/export permission to get export organization ciphers

### PR DESCRIPTION
**Pull request by shane-melton**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Modify the cipher service to allow custom users with the Import/Export permission to retrieve all organization ciphers, which is required when exporting an organization's vault. 

Also see related Clients PR: https://github.com/bitwarden/clients/pull/5014

## Code changes

* **src/Core/Vault/Services/Implementations/CipherService.cs:** Add an additional context check for `AccessImportExport`

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by eliykat** [comment]
I'm not sure about this. This means that the import/export permission gives access to all collections, which is not obvious and might be unintentional. I'm concerned about unintended interaction between custom permissions like this.

I'm also wary of making this change in the service itself rather than on the endpoint, as it could unintentionally open up other unrelated code flows to this permission. We'd have to look at it carefully. (although maybe you already have)

I suggest that a user with import/export custom permission can only export those items they have access to, and we have a big warning if they can only do a partial vault export. We've discussed something like that with upcoming flexible collection changes. Best to check with product though.

**Comment by shane-melton** [comment]
@eliykat Sorry for the delay! I learned a bit more about the desired resolution for this from product today

> I'm not sure about this. This means that the import/export permission gives access to all collections, which is not obvious and might be unintentional. I'm concerned about unintended interaction between custom permissions like this.

Fair point, and I went and checked with product who mentioned that custom permission are to be equivalent to an admin's permissions. So a custom user with the import/export permission is supposed to have access to export all organization ciphers, just like an administrator user. 

> I'm also wary of making this change in the service itself rather than on the endpoint, as it could unintentionally open up other unrelated code flows to this permission. We'd have to look at it carefully. (although maybe you already have)

I did look into this, and the modified service method in this PR is only consumed in 4 different areas client side (no other uses server side that I could see): 
1. **Organization Admin vault** - It is only called if the user has the `canEditAnyCollection` permission. Otherwise, the component uses the ciphers made available in the sync data.
2. **Organization reports** - This use case was already explicitly checked for in the service method
3. **Organization export** - The use case being added and checked in this PR
4. **Delete organization component** - Users must be an owner to delete an organization  

I don't expect any unintentional permissions hiccups with modifying the service based on these uses client side; but if you see anything I might have missed please let me know!

> I suggest that a user with import/export custom permission can only export those items they have access to, and we have a big warning if they can only do a partial vault export. We've discussed something like that with upcoming flexible collection changes. Best to check with product though.

It was also mentioned that after flexible collections, the admin console export page (which will be tied to the permission) will be responsible for all org items; while the individual vault export will be responsible for exporting all items a user has access to (both individual and organizational). So I think this will effectively become the case.

**Review by eliykat — DISMISSED** [review]
Thanks for taking the time to look into this and chase down answers to my various questions.

> the modified service method in this PR is only consumed in 4 different areas client side (no other uses server side that I could see)

There are 2 uses server side: `CipherService.GetOrganizationCiphers` is called by `OrganizationExportController.Export` (this PR) and by `CiphersController.GetOrganizationCollections` (used by some of the front-end components you refer to above).

But at the end of the day, if we're giving access to all ciphers to a user with these permissions, then _they have access to all ciphers_. If another endpoint is doing anything extra, then it needs to contain additional permission checks (e.g. deleting an org). I think you've covered this off above. So this is all OK with me, thanks!

**Comment by shane-melton** [comment]
@eliykat I had to make a few additional tweaks to the `Cipher` and `Collection` services in order to make this work properly.

-  `CollectionService`
   -  Make the same change (that we previously discussed for the `CipherService`) so that users with Import/Export access do not get the unexpected NotFoundException.
   - Modify the method to consider the Import/Export permission when deciding to return the full list of collections vs. only collections the user has been assigned. As previously discussed users with Import/Export need all collections for a proper organization export.
- `CipherService`
   - Make another tweak to actually include all ciphers for users with Import/Export access. The previous change, while allowing access to the endpoint, still only returned ciphers that have been assigned to the user.

I did another dive into the admin console where these changes could affect and I couldn't find anything behaving abnormally. When viewing the vault, custom users with Import/Access still only see their assigned collections throughout the admin console. Its only when they export the org vault that all collections/ciphers become readily available in the exported file.

Happy to further discuss this if you'd like; I'm definitely looking forward to the having those improved auth handlers in the future to make this more straightforward 😅.

**Review by r-tome — DISMISSED** [review]
Looks great!
Just one minor suggestion: Since `_currentContext.AccessImportExport` already checks if the user is an admin for that organization, we can simplify the condition from:
`if (await _currentContext.OrganizationAdmin(organizationId) || await _currentContext.AccessImportExport(organizationId))`

to:
`if (await _currentContext.AccessImportExport(organizationId))`

**Comment by shane-melton** [comment]
Thanks for the feedback/approval @r-tome! I removed that redundant `OrganizationAdmin` check as you suggested.

**Pull request merged**
