### PR TITLE
Add symlink to mssql backup folder with latest backup file

### PR DESCRIPTION
**Pull request by gspfranc**
Small change to have a reference as a symlink to the latest mssql backup file. 
https://community.bitwarden.com/t/add-symlink-to-mssql-backup-folder-with-latest-backup-file/27695

### CODE REVIEW

**Comment by gspfranc** [comment]
Hi @tgreer  @kspearrin,
Got anything to say on this small change?

**Comment by tgreer** [comment]
@gspfranc not sure I have anything to say on this matter... Mistagged?

**Comment by tgreer-bw** [comment]
@tgreer I think I was the target here :-) 

pointing

@gspfranc seems like a useful addition, but up to @kspearrin / @cscharf overall.

**Comment by Hinton** [comment]
Hi @gspfranc,

Is there a particular reason for wanting a symlink to the latest backup? Something like  `ls -t * | head -1` should give you the latest backup.

**Comment by gspfranc** [comment]
Mainly for backup automation with other tools and systems. 
my use case is:
`aws s3 cp /opt/bitwarden/bwdata/mssql/backups/vault_FULL_latest.BAK [s3_url]`

I know that i could inject the file name with `ls -t * | head -1` but I could be a nice to have to always have a symlink to the latest backup. 

It kinds of look like the dateext option in log rotate configs

**Comment by Hinton** [comment]
I'll need to test this, I've used symlinks in containers before, and from memory the symlinks were created using the containers filesystem, not the hosts. Which resulted in symlinks pointing to invalid files, as well as struggling with permissions.

**Comment by Hinton** [comment]
Yea, absolute path symlinks doesn't really work when sharing files between host and containers in docker. Unless they exist in the same folder structure on both host and guest.

```
$ ls -la
-rw-r----- 1 nobody nogroup 2605056 Dec 20 21:13 vault_FULL_20211220_201351.BAK
lrwxrwxrwx 1 nobody nogroup      59 Dec 20 21:13 vault_FULL_latest.BAK -> /etc/bitwarden/mssql/backups/vault_FULL_20211220_201351.BAK
```

Regarding the use case, I would personally want to store more than just the latest backup offsite. Preferably the whole directory since it would give me 30 days of data.

**Comment by Hinton** [comment]
I think we'll want to keep the backup script as lightweight as possible. It's mainly there to provide a basic backup for most self-hosted users. For more complex backup flows I would recommend rolling your own backup script.

It's possible to override the backup script using `docker-compose.override.yml` with a volume overriding the `backup-db.sh` script.

**Pull request closed without merging**
