### PR TITLE
Allow central flags.json

### PR DESCRIPTION
**Pull request by MGibson1**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Allows specification of a central flags.json so that they are shared accross projects

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by coroiu** [comment]
@MGibson1 where do you put the `flags.json` file?

**Review by coroiu — COMMENTED** [review]
@MGibson1 where do you put the `flags.json` file?

**Comment by MGibson1** [comment]
src/flags.json

**Review by coroiu — APPROVED** [review]
Cool

**Pull request merged**
