### PR TITLE
[PM-2284] feat: add pinterest equivilent domains

### PR DESCRIPTION
**Pull request by SethFalco**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

Pinterest.co.uk and Pinterest.com use the same username and password combination.

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

---

I have another PR that does a similar thing which this will have conflicts with.

### Related

* https://github.com/bitwarden/server/pull/2000

### CODE REVIEW

**Comment by djsmith85** [comment]
Hi @SethFalco and thank you for your contribution. 

I did a quick search on this and it seems, we might be able to extend this with more equivalents according to this article: https://medium.com/pinterest-engineering/how-switching-our-domain-structure-unlocked-international-growth-e00c8184d5dd

We'd appreciate if you could find a source detailing all domains owned by Pinterest which redirect to accounts.pinterest.com

**Comment by SethFalco** [comment]
```
  <link rel="alternate" href="ios-app://429047995/pinterest/feed/home">
  <link rel="alternate" href="android-app://com.pinterest/pinterest/">
  <link rel="alternate" href="https://ar.pinterest.com/" hreflang="es-AR">
  <link rel="alternate" href="https://www.pinterest.com.au/" hreflang="en-AU">
  <link rel="alternate" href="https://br.pinterest.com/" hreflang="pt">
  <link rel="alternate" href="https://www.pinterest.cl/" hreflang="es-CL">
  <link rel="alternate" href="https://co.pinterest.com/" hreflang="es-CO">
  <link rel="alternate" href="https://cz.pinterest.com/" hreflang="cs">
  <link rel="alternate" href="https://www.pinterest.de/" hreflang="de">
  <link rel="alternate" href="https://www.pinterest.dk/" hreflang="da">
  <link rel="alternate" href="https://www.pinterest.es/" hreflang="es">
  <link rel="alternate" href="https://fi.pinterest.com/" hreflang="fi">
  <link rel="alternate" href="https://www.pinterest.fr/" hreflang="fr">
  <link rel="alternate" href="https://www.pinterest.co.uk/" hreflang="en-GB">
  <link rel="alternate" href="https://gr.pinterest.com/" hreflang="el">
  <link rel="alternate" href="https://hu.pinterest.com/" hreflang="hu">
  <link rel="alternate" href="https://id.pinterest.com/" hreflang="id">
  <link rel="alternate" href="https://in.pinterest.com/" hreflang="en-IN">
  <link rel="alternate" href="https://it.pinterest.com/" hreflang="it">
  <link rel="alternate" href="https://www.pinterest.jp/" hreflang="ja">
  <link rel="alternate" href="https://www.pinterest.co.kr/" hreflang="ko">
  <link rel="alternate" href="https://nl.pinterest.com/" hreflang="nl">
  <link rel="alternate" href="https://www.pinterest.nz/" hreflang="en-NZ">
  <link rel="alternate" href="https://no.pinterest.com/" hreflang="nb">
  <link rel="alternate" href="https://pl.pinterest.com/" hreflang="pl">
  <link rel="alternate" href="https://www.pinterest.pt/" hreflang="pt-PT">
  <link rel="alternate" href="https://ro.pinterest.com/" hreflang="ro-RO">
  <link rel="alternate" href="https://ru.pinterest.com/" hreflang="ru">
  <link rel="alternate" href="https://www.pinterest.se/" hreflang="sv">
  <link rel="alternate" href="https://sk.pinterest.com/" hreflang="sk">
  <link rel="alternate" href="https://tr.pinterest.com/" hreflang="tr">
  <link rel="alternate" href="https://za.pinterest.com/" hreflang="en-ZA">
  <link rel="alternate" href="https://www.pinterest.com/" hreflang="en">
```

Taken from the `<head>` of the pinterest.com website. :thinking: 
Think we can just take from this?

I think we can omit subdomains of `pinterest.com` since that's covered by pinterest.com.

* pinterest.com
* pinterest.com.au
* pinterest.cl
* pinterest.de
* pinterest.dk
* pinterest.es
* pinterest.fr
* pinterest.co.uk
* pinterest.jp
* pinterest.co.kr
* pinterest.nz
* pinterest.pt
* pinterest.se

Can we do the apps here as well?
* android-app://com.pinterest/pinterest/
* ios-app://429047995/pinterest/feed/home

**Comment by SethFalco** [comment]
Updated the list of domains with only the domains. (Not Android/iOS URIs since I wasn't sure how to approach that, advice welcome!)

Meanwhile, I hope this is fine!

**Review by djsmith85 — APPROVED** [review]
@SethFalco: Sorry for the delay in reviewing this. The changes are looking good and this is ready to get merged. Thank you for your contribution.

**Pull request merged**
