### PR TITLE
GlobalDomains lists modified

### PR DESCRIPTION
**Pull request by vicmonf1**

### CODE REVIEW

**Comment by kspearrin** [comment]
Why did we deprecate google?

**Comment by vicmonf1** [comment]
I commented it on the 3rd commit. The google list included google.com, youtube.com and gmail.com. I just realised that youtube.com and gmail.com just doesn't have any login form

The login is done on accounts.google.com and youtube.com domain gets Oauth info. (gmail.com is just a domain that resolves to mail.google.com, a subdomain of google.com)

**Comment by vicmonf1** [comment]
A related question, would you like to have some androidapp:// domains on the StaticStore?

**Comment by kspearrin** [comment]
@vicmonf1 Perhaps, yes, we could start to include androidapp:// items in the global domains as well, though it should only be needed where the current detection methods fail to find the proper credentials.

**Comment by eliykat** [comment]
Hi @vicmonf1, I'm currently reviewing and cleaning up old pull requests. If you're still interested in progressing this PR, please:
* sign the Contributor License Agreement (see the link provided by the CLAassistant bot above)
* review/respond to any outstanding change requests or questions
* reply here and tag me (@) so that I can mark it for further review

As this PR is more than 12 months old, I'll close it for now. However, this is just housekeeping. We encourage our community members to get involved and make contributions, so you can comment here even after it's closed and I'll reopen it if required.

Thanks again for your submission!

**Pull request closed without merging**
