### PR TITLE
Cleanup Projects

### PR DESCRIPTION
**Pull request by justindbaur**
In a follow up to #1314 I first noticed that I had missed removing the unneeded props from the `csproj` files in `bitwarden_license/*`. So I cleaned those up. 

Also since we discussed how this could have an effect on the embedded resource names I added tests to the `Icons` and `Core` projects that have embedded resources to ensure that the names of the resources are as expected.

### CODE REVIEW

**Review by cscharf — APPROVED** [review]
Great, thank you!

**Comment by cscharf** [comment]
Hi @justindbaur , got this from our CI/CD pipeline on build, https://github.com/bitwarden/server/runs/2579042244?check_suite_focus=true#step:8:36

Any thoughts (before I dig in)?

```
Error: D:\a\server\server\test\Core.Test\Services\OrganizationServiceTests.cs(76,44): error CS0234: The type or namespace name 'Business' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\OrganizationServiceTests.cs(77,37): error CS0234: The type or namespace name 'Business' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\OrganizationServiceTests.cs(78,37): error CS0234: The type or namespace name 'Business' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\OrganizationServiceTests.cs(79,37): error CS0234: The type or namespace name 'Business' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\OrganizationServiceTests.cs(80,60): error CS1503: Argument 4: cannot convert from 'System.Collections.Generic.List<Bit.Core.Test.Models.Business.ImportedOrganizationUser>' to 'System.Collections.Generic.IEnumerable<Bit.Core.Models.Business.ImportedOrganizationUser>' [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\OrganizationServiceTests.cs(140,44): error CS0234: The type or namespace name 'Business' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\OrganizationServiceTests.cs(141,37): error CS0234: The type or namespace name 'Business' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\OrganizationServiceTests.cs(142,37): error CS0234: The type or namespace name 'Business' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\OrganizationServiceTests.cs(143,37): error CS0234: The type or namespace name 'Business' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\OrganizationServiceTests.cs(144,60): error CS1503: Argument 4: cannot convert from 'System.Collections.Generic.List<Bit.Core.Test.Models.Business.ImportedOrganizationUser>' to 'System.Collections.Generic.IEnumerable<Bit.Core.Models.Business.ImportedOrganizationUser>' [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\DeviceServiceTests.cs(21,37): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\AutoFixture\OrganizationFixtures.cs(76,38): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\AutoFixture\OrganizationFixtures.cs(77,34): error CS1503: Argument 2: cannot convert from 'System.Guid' to 'System.Func<?>' [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\AutoFixture\OrganizationFixtures.cs(78,37): error CS1503: Argument 2: cannot convert from 'short' to 'System.Func<?>' [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\AutoFixture\OrganizationFixtures.cs(51,38): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\AutoFixture\OrganizationFixtures.cs(52,40): error CS1503: Argument 2: cannot convert from 'Bit.Core.Enums.PlanType' to 'System.Func<?>' [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\AutoFixture\OrganizationFixtures.cs(60,38): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\AutoFixture\OrganizationFixtures.cs(40,38): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\AutoFixture\OrganizationFixtures.cs(41,40): error CS1503: Argument 2: cannot convert from 'Bit.Core.Enums.PlanType' to 'System.Func<?>' [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\AutoFixture\OrganizationFixtures.cs(23,38): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\AutoFixture\OrganizationFixtures.cs(24,34): error CS1503: Argument 2: cannot convert from 'System.Guid' to 'System.Func<?>' [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\AutoFixture\OrganizationFixtures.cs(25,41): error CS1503: Argument 2: cannot convert from 'bool' to 'System.Func<?>' [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\CollectionServiceTests.cs(43,41): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\CollectionServiceTests.cs(58,47): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\CollectionServiceTests.cs(73,45): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\CollectionServiceTests.cs(88,47): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\CollectionServiceTests.cs(105,45): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\CollectionServiceTests.cs(119,47): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\CollectionServiceTests.cs(124,47): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\CollectionServiceTests.cs(140,45): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\CollectionServiceTests.cs(152,47): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\CollectionServiceTests.cs(157,50): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
Error: D:\a\server\server\test\Core.Test\Services\CollectionServiceTests.cs(173,45): error CS0234: The type or namespace name 'Table' does not exist in the namespace 'Bit.Core.Test.Models' (are you missing an assembly reference?) [D:\a\server\server\test\Core.Test\Core.Test.csproj]
```

**Comment by justindbaur** [comment]
@cscharf  Yeah so it appears that changing the one namespace in `CipherTests` from `Core.Test.Models` to `Bit.Core.Test.Models` confused some other type definitions that were partially qualified. I will have a new PR to fix it in 10 minutes or so.

**Comment by cscharf** [comment]
Thank you

**Pull request merged**
