### PR TITLE
Fix: Not sourcing the .env file when executing docker-compose

### PR DESCRIPTION
**Pull request by haneef95**
## Type of change
- [x] Bug fix
- [x] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

As per [Docker Specs/Docs](https://docs.docker.com/compose/environment-variables/#the-env-file), the .env file in the same directory as docker-compose.yml should be used for defining variables used in the docker-compose files and to specify [Compose CLI environment variables](https://docs.docker.com/compose/reference/envvars/) like `COMPOSE_PROJECT_NAME`

This should also avoid the naming of networks with generic and confusing names like:
- docker_default
- docker_public

This commit should resolve the issue that has been raised both in Github and in the forum, some below:
https://community.bitwarden.com/t/appropriate-naming-of-bitwarden-docker-networks-and-containers/35341
https://community.bitwarden.com/t/docker-compose-project-name/15442

## Code changes

* **file.ext:** Description of what was changed and why
`set -a`: "Each variable or function that is created or modified is given the export attribute and marked for export to the environment of subsequent commands."
"Using ‘+’ rather than ‘-’ causes these options to be turned off."
Source: [The Set Builtin](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html)

## Before you submit
- [ ] If making database changes - I have also updated Entity Framework queries and/or migrations
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Comment by vgrassia** [comment]
@haneef95 From my testing, `docker-compose` currently reads the `.env` file without any modification to the `run.sh` script.  I used the value `testproject` for `COMPOSE_PROJECT_NAME` and the networks `testproject_default` and `testproject_public` were created.  Can you test this and confirm?

**Comment by haneef95** [comment]
Thanks @vgrassia.

Could you confirm where you placed the `.env` file?

If the `.env` files was placed in the same directory as `$PWD`, it currently doesn't work from any other directory. Which could lead to inconsistencies, for obvious reasons.

However, if the exact same `.env` file is sourced and exported to the environment all the time (as done with this PR), it'll give it consistency.

**Comment by haneef95** [comment]
@vgrassia - erm... that's strange... It doesn't work for me that way.

It only works if `.env` is in the `$PWD`.

Which OS was this on by the way? I'm on Ubuntu 21.04

Not sure if anyone else is facing this same issue...

**Comment by vgrassia** [comment]
@haneef95 It looks like it *only* works for me if the `.env` file is in the `bwdata/docker` directory.  When I put the `.env` file in the same directory as `bitwarden.sh`, it doesn't use it. I'm also using `Ubuntu 21.04`. Docker version is `20.10.11` and docker-compose version is `1.29.2`.

**Comment by haneef95** [comment]
Official answer to our predicament:

> Declare default environment variables in file
> Compose supports declaring default environment variables in an environment file named .env placed in the project directory. Docker Compose versions earlier than 1.28, load the .env file from the current working directory, where the command is executed, or from the project directory if this is explicitly set with the --project-directory option. This inconsistency has been addressed starting with +v1.28 by limiting the default .env file path to the project directory.
https://docs.docker.com/compose/env-file/

So, this PR should help with compatibility of earlier versions of `docker-compose`.

**Comment by cscharf** [comment]
Hi @haneef95 , thank you for the PR and contribution. At this time we're going to decline these changes. For those using an older version of docker-compose, they can work around this issue by using a `docker-compose override` file if need be.

**Pull request closed without merging**
