### PR TITLE
Add lock files for NuGet

### PR DESCRIPTION
**Pull request by Hinton**
## Type of change
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [x] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Adds lockfiles to the projects, and configures the build pipeline to cache nuget packages. Also informs msbuild to use the lockfiles.

This drastically speeds up the restore process, from ~7-8min to less than 1min.

## Code changes

* **.github/workflows/build.yml:** Added cache action, set env variable to store nuget packages in the workspace. Configured msbuild restore to use lock files.
* ***.csproj**: Added `<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>` to generate lockfiles on restore.
* ***/packages.lock.json**: Added lock files.

## Testing requirements

Ensure it builds?

## Before you submit
- [ ] I have checked for formatting errors (`dotnet tool run dotnet-format --check`) (required)
- [ ] If making database changes - I have also updated Entity Framework queries and/or migrations
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Comment by joseph-flinn** [comment]
Looks good to me. But I'll defer to @cscharf with his .NET expertise in how package lock files will work.

**Review by cscharf — DISMISSED** [review]
@joseph-flinn , FYI, The lock file is a tool (NuGet) generated file and should never be manually edited; so these should be good to go if the `yaml` looks good. The CSPROJ edits look good to me as well.

**Comment by justindbaur** [comment]
If this entry goes into every `csproj` file would it be simpler to add it to the `Directory.Build.props` file instead?

**Comment by Hinton** [comment]
@justindbaur Good catch, I've moved the code.

**Pull request merged**
