### PR TITLE
Added netcup to global equivalent domains list

### PR DESCRIPTION
**Pull request by ntimo**
Added netcup.de netcup.eu and the customercontrolpanel to the global domains list.

### CODE REVIEW

**Comment by kspearrin** [comment]
Are these popular services in Germany? Need more context as to why this would be a valid global equivalent domain for the masses.

**Comment by ntimo** [comment]
Its a big German server hosting company. The .eu site is the english site and the .de the German one and the customercontrolpanel.de is the well the customercontrolpanel for customers to manage there products and servers and stuff.

**Comment by lgaida** [comment]
I can confirm that netcup is a well-known (webhosting|server|domain|certificate) provider!

**Comment by nedimAT** [comment]
+1

**Comment by Caspar78** [comment]
+1

**Comment by pzillmann** [comment]
+1

**Comment by killerbees19** [comment]
+1

**Comment by kooptim** [comment]
+1

**Comment by gxf0** [comment]
+1

**Comment by LabSen** [comment]
+1

**Comment by sebthom** [comment]
@ntimo can you please rebase and solve the conflicts. I would also like to see this merged :-)

**Pull request merged**
