### PR TITLE
added configuration options for ForwardedHeaders

### PR DESCRIPTION
**Pull request by theSuess**
This allows for the use of load balancers not connected via localhost

### CODE REVIEW

**Comment by kspearrin** [comment]
Ok. Can you explain what type of setup you have here that is requiring these headers vs a regular installation?

**Comment by theSuess** [comment]
Our BitWarden setup is running on OpenShift. With this setup, each project has a different IP. When nginx is passing the X-Forwarded-For headers upstream, the API does not use this information as the nginx ip is not in its list of KnownProxies or KnownNetworks

**Comment by kspearrin** [comment]
> each project has a different IP

Do you mean each Bitwarden project (API, Admin, etc) or something else?

**Comment by theSuess** [comment]
yes, that's the issue

**Comment by kspearrin** [comment]
If Admin and API have different proxy IP addresses then this solution would not work. You have it specified in global settings, which there is only one of (defined in global env file) that will apply to all containers.

**Comment by theSuess** [comment]
Admin and API get served by the same proxy but they reject the headers

**Comment by eliykat** [comment]
Hi @theSuess, I'm currently reviewing and cleaning up old pull requests. If you're still interested in progressing this PR, please:
* sign the Contributor License Agreement (see the link provided by the CLAassistant bot above)
* review/respond to any outstanding change requests or questions
* reply here and tag me (@) so that I can mark it for further review

As this PR is more than 12 months old, I'll close it for now. However, this is just housekeeping. We encourage our community members to get involved and make contributions, so you can comment here even after it's closed and I'll reopen it if required.

Thanks again for your submission!

**Pull request closed without merging**
