### PR TITLE
Implement workaround to get correct client IP for self-hosted instances

### PR DESCRIPTION
**Pull request by karelvanhecke**
Should fix [issue#463](https://github.com/bitwarden/server/issues/463)

### CODE REVIEW

**Comment by kspearrin** [comment]
I don't think this is going to give you want you expect. For instance, just visit `yourdomain.com/api/ip` to see a dump of the headers for a request. The real IP is nowhere to be found.

**Comment by karelvanhecke** [comment]
I just checked, X-Forwarded-For contains my real client IP adress + the IP adres of my first reverse proxy as expected.

**Comment by kspearrin** [comment]
This solution seems t be rather easily forged:

```
curl -X GET \
  https://bw.domain.com/api/ip \
  -H 'X-Forwarded-For: 1.1.1.1' \
  -H 'cache-control: no-cache'
```

```
{
    "Ip": "::ffff:172.18.0.10",
    "Headers": {
        "Cache-Control": [
            "no-cache"
        ],
        "Connection": [
            "close"
        ],
        "Accept": [
            "*/*"
        ],
        "Accept-Encoding": [
            "gzip, deflate"
        ],
        "Host": [
            "bw.domain.com"
        ],
        "User-Agent": [
            "PostmanRuntime/7.6.1"
        ],
        "X-Real-IP": [
            "172.18.0.1"
        ],
        "X-Forwarded-For": [
            "1.1.1.1, 172.18.0.1"
        ],
        "X-Url-Scheme": [
            "https"
        ],
        "X-Forwarded-Proto": [
            "https"
        ]
    }
}
```

**Comment by karelvanhecke** [comment]
> 
> 
> This solution seems to be rather easily forged:
> 
> ```
> curl -X GET \
>   https://bw.domain.com/api/ip \
>   -H 'X-Forwarded-For: 1.1.1.1' \
>   -H 'cache-control: no-cache'
> ```
> 
> ```
> {
>     "Ip": "::ffff:172.18.0.10",
>     "Headers": {
>         "Cache-Control": [
>             "no-cache"
>         ],
>         "Connection": [
>             "close"
>         ],
>         "Accept": [
>             "*/*"
>         ],
>         "Accept-Encoding": [
>             "gzip, deflate"
>         ],
>         "Host": [
>             "bw.domain.com"
>         ],
>         "User-Agent": [
>             "PostmanRuntime/7.6.1"
>         ],
>         "X-Real-IP": [
>             "172.18.0.1"
>         ],
>         "X-Forwarded-For": [
>             "1.1.1.1, 172.18.0.1"
>         ],
>         "X-Url-Scheme": [
>             "https"
>         ],
>         "X-Forwarded-Proto": [
>             "https"
>         ]
>     }
> }
> ```

Almost every header field can be forged. I don't know why you can't reproduce the same results. You could lookup public Bitwarden instances on shodan.io and you'll see that they produce the same result as mine.

**Comment by kspearrin** [comment]
It seems the only winning combination is Linux host with non-localhost domain.

According to this test, we would want the last IP in the header to prevent forging?

```
curl -X GET \
  https://bitwarden.domain.com/api/ip \
  -H 'X-Forwarded-For: 1.1.1.1' \
  -H 'cache-control: no-cache'
```

```
{
    "Ip": "::ffff:172.24.0.10",
    "Headers": {
        "Cache-Control": [
            "no-cache"
        ],
        "Connection": [
            "close"
        ],
        "Accept": [
            "*/*"
        ],
        "Accept-Encoding": [
            "gzip, deflate"
        ],
        "Host": [
            "bitwarden.domain.com"
        ],
        "User-Agent": [
            "PostmanRuntime/7.6.1"
        ],
        "X-Real-IP": [
            "xx.xx.xx.xx"
        ],
        "X-Forwarded-For": [
            "1.1.1.1, xx.xx.xx.xx"
        ],
        "X-Url-Scheme": [
            "https"
        ],
        "X-Forwarded-Proto": [
            "https"
        ]
    }
}
```

`xx.xx.xx.xx` is my client IP.

**Comment by kspearrin** [comment]
My guess here is that we need to properly configure the `KnownProxies` property in `ForwardedHeadersOptions`.

**Comment by karelvanhecke** [comment]
CloudFlare explains this quite well: https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-CloudFlare-handle-HTTP-Request-headers-

X-Forwarded-For is just as hard to prevent from being forged as a user-agent.
Your solution wouldn't work as every proxy appends its IP address to X-Forwarded-For after the client IP address.

A solution similar to CF's CF-Connecting-IP could be used, but it'd have to be done at the first reverse proxy.

**Comment by karelvanhecke** [comment]
> 
> 
> My guess here is that we need to properly configure the `KnownProxies` property in `ForwardedHeadersOptions`.
> 
> See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#forwarded-headers-middleware-options

This would limit users to using just the standard Bitwarden installation. Adding additional reverse proxies/load balancers/WAF's or even a CDN in front of your installation wouldn't produce the correct result.

**Comment by kspearrin** [comment]
Can't we just make it configurable by the user with an environment variable? They can add whatever known proxies they are using.

**Comment by karelvanhecke** [comment]
> 
> 
> Can't we just make it configurable by the user with an environment variable? They can add whatever known proxies they are using.

That could work. 
But what about the NGINX docker container? I wonder why it doesn't append it's IP address to X-Forwarded-For. It should, right? At least it's configured to.

**Comment by kspearrin** [comment]
See https://github.com/bitwarden/server/commit/e6baa1490ce7a1cc90ec654dacb56e02618c3e90

You can now add:

```
globalSettings__knownProxies=1.1.1.1,2.2.2.2,3.3.3.3
```

You can try this in the `dev` tags on DockerHub whenever the CI finishes building.

Just edit the versions referenced in `bitwarden.sh` to "dev" and then `./bitwarden.sh update`.

**Comment by karelvanhecke** [comment]
> 
> 
> See [e6baa14](https://github.com/bitwarden/server/commit/e6baa1490ce7a1cc90ec654dacb56e02618c3e90)
> 
> You can now add:
> 
> ```
> globalSettings__knownProxies=1.1.1.1,2.2.2.2,3.3.3.3
> ```
> 
> You can try this in the `dev` tags on DockerHub whenever the CI finishes building.
> 
> Just edit the versions referenced in `bitwarden.sh` to "dev" and then `./bitwarden.sh update`.

@kspearrin That doesn't seem to solve it.
What if we stopped using X-Forward-For and switched to X-Real-IP or a header of our choice.

https://nginx.org/en/docs/http/ngx_http_realip_module.html
The module above seems to set the correct IP address based on the last trusted proxy address. X-Real-IP should already contain the correct IP address for standard installations with one proxy. Those with additional proxies would have to define them, but it wouldn't require any major changes in the Bitwarden server code.

**Comment by kspearrin** [comment]
You can try dev tag again when these build:

https://github.com/bitwarden/server/commit/a416f5a91289309469e41c8187558e7644d74205
https://github.com/bitwarden/server/commit/f951304f115884f45b501cc5263bcb208454559c

I have not tested yet, so not sure if I did the `--with-http_realip_module` option correct.

**Comment by karelvanhecke** [comment]
you should revert f951304f115884f45b501cc5263bcb208454559c.
--with-http_realip_module is a build option. I've checked and this module enabled.

We'll need an additional config file for nginx containing the following:
```
set_real_ip_from <proxy_ip/network>;
real_ip_header X-Real-IP; #Default value, doesn't need to be specified explicitly.
real_ip_recursive off; #Default value, doesn't need to be specified explicitly
```

Where <proxy_ip> can be set from config.yml. The config file above will have to be rebuild when config.yml changes and should only be included when at least one proxy IP is specified. This variable should accept multiple addresses, but also CIDR notations should be allowed (sockets won't be necessary).
Each value specified will have to get it's own line in the config file.

For example:
```
set_real_ip_from  192.168.1.0/24;
set_real_ip_from  192.168.2.1;
set_real_ip_from  2001:0db8::/32;
```

**Comment by kspearrin** [comment]
reverted and pushed https://github.com/bitwarden/server/commit/6dc2e1b328e672ca6aa5388ce45eaea076abee21

Still haven't gotten around to testing myself yet. Thanks.

**Comment by karelvanhecke** [comment]
https://github.com/bitwarden/server/blob/6dc2e1b328e672ca6aa5388ce45eaea076abee21/util/Setup/Templates/NginxConfig.hbs#L55

Slight syntax error,  there should be a `;` behind `set_real_ip_from {{{Value}}}`

Other than that everything seems correct. I'll be sure to test it tonight.

**Comment by kspearrin** [comment]
Fixed

**Comment by karelvanhecke** [comment]
One thing I've noticed, `X-Forwarded-For` now contains duplicate values when an additional reverse proxy is used.
For example:
`X-Forwarded-For: a.a.a.a, a.a.a.a`
where a.a.a.a = client IP
While this doesn't affect anything, people might want the correct values in their logs.

This is because `"$proxy_add_x_forwarded_for"` is equal to `"$http_x_forwarded_for,$remote_addr"` and the real IP module overrides `$remote_addr`.

Changing
`proxy_set_header X-Forwarded-For "$proxy_add_x_forwarded_for"`
to
`proxy_set_header X-Forwarded-For "$http_x_forwarded_for,$realip_remote_addr"`
when a trusted proxy is specified will also keep the correct values for the `X-Forwarded-For` field.

I've read over the docs for this module again and came to the conclusion that the following configuration options might be useful.
```
real_ip_header    X-Forwarded-For;
real_ip_recursive on;
```

Using these configuration options allows users to define all of their proxies/lbs/wafs in config.yml, rather than having to change the configuration of their proxies/lbs/wafs itself.

Example using those configuration options:

`client (a.a.a.a) -> LB (b.b.b.b) -> WAF (c.c.c.c) -> Bitwarden nginx -> Bitwarden server`
The user specifies the IP addresses of their LB and WAF in Bitwarden's config.yml.

When a request reaches Bitwarden's nginx instance `X-Forwarded-For` contains `a.a.a.a, b.b.b.b`, Bitwarden's nginx instance will properly append `c.c.c.c ` to ` X-Forwarded-For`. `X-Real-IP` will be set to the last non trusted IP address (rightmost value that is not a trusted IP address) in `X-Forwarded-For`. In this case: `a.a.a.a`.

This still prevents spoofing and keeps `X-Forwarded-For` correct, following best practices.

If you have any questions, feel free to ask. Thanks for the fast cooperation.

**Comment by kspearrin** [comment]
Unfortunately `proxy_set_header X-Forwarded-For "$proxy_add_x_forwarded_for"` is set in the `proxy.conf` file, which isnt generated based on `config.yml` today.

If I added `proxy_set_header X-Forwarded-For "$http_x_forwarded_for,$realip_remote_addr"` it to `default.conf` when `real_ips` are set, will it override the value from `proxy.conf`?

I don't think X-Real-IP can be spoofed with the configuration that we already have. I tried, but it didn't work and still showed the proper client IP.

**Comment by karelvanhecke** [comment]
> 
> 
> Unfortunately `proxy_set_header X-Forwarded-For "$proxy_add_x_forwarded_for"` is set in the `proxy.conf` file, which isnt generated based on `config.yml` today.
> 
> If I added `proxy_set_header X-Forwarded-For "$http_x_forwarded_for,$realip_remote_addr"` to `default.conf` when `real_ips` are set, will it override the value from `proxy.conf`?
> 
> I don't think X-Real-IP can be spoofed with the configuration that we already have. I tried, but it didn't work and still showed the proper client IP.

NGINX doesn't handle configuration files that way if I remember correctly. I'm fairly certain it'll throw an error when added that way.

We'll just leave X-Forwarded-For as it is for now, since we don't use it anywhere. It'll contain the client IP twice when Real IP is used, but only if the request came from an already known proxy.

But we should still use the following options:
```
real_ip_header    X-Forwarded-For;
real_ip_recursive on;
```
It won't affect anything, except allow the user to use multiple proxies (chained) in front of their Bitwarden installation and it'll produce the correct client IP address, as long as the user specifies all his trusted proxies in config.yml.

Example:
`X-Forwarded-For: <spoofed_ip>, a.a.a.a, b.b.b.b`
where b.b.b.b is a known proxy and the this request comes from c.c.c.c, another known proxy, it'll use a.a.a.a for X-Real-IP, without the user needing to change their configurations on their other proxies.

**Comment by kspearrin** [comment]
See https://github.com/bitwarden/server/commit/b935b16cb8ef7cd69eb2d5367ab32b81f89566d5

**Pull request closed without merging**
