### PR TITLE
Move identity endpoints to Identity service

### PR DESCRIPTION
**Pull request by Hinton**
## Type of change
- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Move some account related endpoints used for logging in to the identity service. I've duplicated the code, and marked the old as deprecated. We unfortunately can't remove them "now" and have to wait a bit until we are comfortable with comparability with older clients.

I've also renamed `AccountController` in `Identity` to `SsoController`, since it only handles Sso interactions, and to avoid confusion with the new `AccountsController`.

## Code changes

- **src/Api/Controllers/AccountsController.cs** Deprecated the `prelogin` and `register` endpoints.
- **src/Identity/Controllers/AccountsController.cs**: Duplicated `prelogin` and `register` endpoints from `Api`.
- **src/Identity/Controllers/SsoController.cs**: Removed some unused DI fields. Renamed from `AccountController`, and changed primary endopint to `sso/[Action]`. `account/[Action]` is keept for now.

## Before you submit
- [ ] I have checked for formatting errors (`dotnet tool run dotnet-format --check`) (required)
- [ ] If making database changes - I have also updated Entity Framework queries and/or migrations
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Comment by Hinton** [comment]
I would also like to propose renaming the existing `AccountController` to `SsoController` since it's only used during sso flows, and replace the endpoint from `account` to `sso`. (With a temporary alias to account) I believe this would help with the mental model of the Identity service, since those endpoints are only used in combination with sso.

**Comment by Hinton** [comment]
Not purely, but they all interact primarily with the user in my opinion.

**Comment by cscharf** [comment]
Let's reserve those to the API for now since they're not really authentication actions.

**Review by cscharf — APPROVED** [review]
Looks good, thanks Oscar!

**Pull request merged**
