### PR TITLE
Allow organization owner and admins to import users and groups

### PR DESCRIPTION
**Pull request by h44z**
Currently only admin's are allowed to import data (from Active Directory for example).
This patch also grants the import permission to organization owners.

### CODE REVIEW

**Comment by kspearrin** [comment]
This method already allows Owners and Admins. I don't think that this is necessary.

        public bool OrganizationAdmin(Guid orgId)
        {
            return Organizations?.Any(o => o.Id == orgId &&
                (o.Type == OrganizationUserType.Owner || o.Type == OrganizationUserType.Admin)) ?? false;
        }

**Comment by h44z** [comment]
> This method already allows Owners and Admins. I don't think that this is necessary.
> 
> ```
>     public bool OrganizationAdmin(Guid orgId)
>     {
>         return Organizations?.Any(o => o.Id == orgId &&
>             (o.Type == OrganizationUserType.Owner || o.Type == OrganizationUserType.Admin)) ?? false;
>     }
> ```
Hm yes you are right. But somehow it did not work in the latest release with the directory connector. Using the organization owner gives a 404, using an organization admin works. And this is the only place where a 404 gets thrown I think?

**Comment by kspearrin** [comment]
I am not sure why that would happen. Are you sure this owner account belongs to the organization you have selected under Settings?

**Comment by h44z** [comment]
I can currently not check this as we set up an admin user which fixed the problem. Closing this for now.

**Pull request closed without merging**
