### PR TITLE
[EC-529] fix: missing constructor DI assignment

### PR DESCRIPTION
**Pull request by coroiu**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Server throws error when providers try to access an org vault that they are not a member of. Issue is caused when the server tries to log the access because a required dependency is not properly injected (assignment missing in constructor).

## Code changes
* **CipherService.cs:** Add missing statement

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by Hinton** [comment]
I think this is a deeper problem. I don't understand why we're calling the provider here instead of just creating an organization event here?

We should be using
```
            await _eventService.LogOrganizationEventAsync(organization, EventType.Organization_VaultAccessed);
```

in the CipherService instead, since ProviderService is NOOP in the OSS build.

**Comment by Hinton** [comment]
At a second look, I think we should move back https://github.com/bitwarden/server/pull/2128/files#diff-248d35068ce1e3000a48dd60d3aa30b4fdbfae4131fdb88fdd3412a1f4b7b23bL248-L252 to the `CipherController`. It's not exposed anywhere else.

**Comment by r-tome** [comment]
@Hinton the behavior change was not intentional. That refactor's goal was to share the code between `CiphersController` and `OrganizationExportController`.

Couldn't we fix it by calling the `EventService` directly on the `CipherService`?

**Comment by Hinton** [comment]
We only want to emit that event if a provider user enters the organizations vault, i.e grabs a list of all ciphers. Exporting has it's own event.

**Pull request merged**
