### PR TITLE
fixed something shameful

### PR DESCRIPTION
**Pull request by addisonbeck**
Please do not look at this

### CODE REVIEW

**Review by cscharf — APPROVED** [review]
🙀

**Comment by mportune-bw** [comment]
I had to look

**Comment by tgreer-bw** [comment]
Me too 😬👀👀👀👀

**Comment by cscharf** [comment]
Haha, this is mostly my fault, I'll take the blame, I missed this in the initial review, and of course the method refactor was based on my feedback, sooo.... owned 😁  (I won't let you take all the heat @addisonbeck)

**Comment by kgar** [comment]
Sorry, had to look 👀

**Pull request merged**
