### PR TITLE
feat(unpwnpassword): add pwned state and last check date to database

### PR DESCRIPTION
**Pull request by raddatzk**
After reading [this](https://www.theverge.com/tldr/2019/3/5/18252150/bad-password-security-data-breach-taiwan-ji32k7au4a83-have-i-been-pwned) I thought about improving the validation of every password in the vault with [haveibeenpwned](https://haveibeenpwned.com/)

This pull request adds two columns in the cipher table:
- pwned
- pwnedCheckDate

_pwned_ shows if the password is exposed, while _pwnedCheckDate_ holds the datetime of last check. Keeping this centralized gives the ability, to show in every UI, if the password is potentially insecure by already being exposed. Also, with _pwnedCheckDate_, the UI can check in a regular cicle, of seven days for example, if the password is exposed.

Followup pull requests:
- [jslib](https://github.com/bitwarden/jslib/pull/30)

### CODE REVIEW

**Comment by chronm** [comment]
This PR is currently in a draft status, as I don't know the current status of the PR is capable on updating an existing database

**Comment by chronm** [comment]
Okay got it

**Comment by chronm** [comment]
I don't get the draft status away

**Comment by eliykat** [comment]
Hi @raddatzk, thanks for your submission! I'm currently working through and reviewing community PRs with our Product & Engineering team. Unfortunately we've decided not to accept your PR because there is not a demonstrated need for these features and they don't meet the development roadmap priorities.

We definitely welcome community contributions. If you'd like to make any contributions in the future, I recommend raising it for discussion in the [community forums](https://community.bitwarden.com/c/github-contributions/) before starting to write code, so that we can make this evaluation early and provide any guidance required to make sure it can be merged.

**Pull request closed without merging**
