### PR TITLE
[PM-11345] Add SCIM to Teams Plan

### PR DESCRIPTION
**Pull request by amorask-bitwarden**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-11345

## 📔 Objective

1. Add SCIM to the Teams Plan for new customers
2. Update existing Teams Organizations by giving them access to SCIM

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Review by cturnbull-bitwarden — APPROVED** [review]
👨‍🍳

**Comment by amorask-bitwarden** [comment]
@rkac-bw @withinfocus Mind if I ask for a review on this from you two for dbops?

**Comment by amorask-bitwarden** [comment]
@cturnbull-bitwarden @rkac-bw Can I get another look at this after implementing Robert's suggestion?

**Review by cturnbull-bitwarden — DISMISSED** [review]

**Review by rkac-bw — APPROVED** [review]
LGTM

**Pull request merged**
