### PR TITLE
[PM-2300] Add Linux script to create dev certificates 

### PR DESCRIPTION
**Pull request by cas--**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other
```

## Objective

To be able to quickly generate the self-signed certificates for local development on Linux.

## Code changes

* Add a script based on the macOS script that can be used on Linux, either Debian or Red-hat derived distros.
* Trivial fix for json sample file

This may require a documentation update in to [getting-started](https://contributing.bitwarden.com/getting-started/server/guide/#generate-certificates). Please advise who should make those changes.

### CODE REVIEW

**Comment by justindbaur** [comment]
Hi @cas-- Thank you so much for this, I had actually worked on something very similar but never took it across the finish line but now that you've done this I have approval power 😆.  The main difference I see is you using the certificate store manager CLI for the main distros vs me using some tool but I'm fine not doing. 

Do you have any interest in writing a PR for the docs that explain how to use it? I think it would go in this section here: https://github.com/bitwarden/contributing-docs/blob/e77e584d0d63466bedefe849ec060369b287d77b/docs/getting-started/server/guide.md?plain=1#L219 
If not I can work on adding that and we will merge this once it's ready to go.

**Review by justindbaur — APPROVED** [review]
Thank you very much for the contribution, this will be very useful!

**Comment by cas--** [comment]
@justindbaur Thanks for accepting my change, apologies that I don't have time to provide docs updates

**Comment by justindbaur** [comment]
@cas-- No problem at all, we've already got them written and will hopefully be using this script to add dev containers for even easier contributions. Thank you so much for this.

**Pull request merged**
