### PR TITLE
Add Trenitalia sites as equivalent domains

### PR DESCRIPTION
**Pull request by xates**

### CODE REVIEW

**Comment by kspearrin** [comment]
All of these domains seemed to redirect to the same place for me. Where are they used separately for logging into services?

**Comment by xates** [comment]
http://www.trenitalia.com -> https://www.lefrecce.it

screenshot

trenitalia.it isn't actually used anymore, so I'll delete it.

**Comment by xates** [comment]
What do you think?

**Comment by xates** [comment]
@kspearrin Why wasn't this merged?

**Comment by eliykat** [comment]
Hi @xates, I'm currently reviewing and cleaning up old pull requests. If you're still interested in progressing this PR, please:
* sign the Contributor License Agreement (see the link provided by the CLAassistant bot above)
* review/respond to any outstanding change requests or questions
* reply here and tag me (@) so that I can mark it for further review

As this PR is more than 12 months old, I'll close it for now. However, this is just housekeeping. We encourage our community members to get involved and make contributions, so you can comment here even after it's closed and I'll reopen it if required.

Thanks again for your submission!

**Pull request closed without merging**
