### PR TITLE
[PM-5313] Upgrade to SQL Server 2022

### PR DESCRIPTION
**Pull request by withinfocus**
## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [X] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Moves from 2019 to 2022 and enables us to use new language features in scripts and the cloud.

## Code changes

* **util/MsSql/Dockerfile:** Base image change.

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by withinfocus** [comment]
Relates to #3548.

**Review by rkac-bw — DISMISSED** [review]
looks good to me

**Review by vgrassia — APPROVED** [review]

**Review by rkac-bw — DISMISSED** [review]
Looks good to me

**Review by rkac-bw — APPROVED** [review]
Looks good to me

**Pull request merged**
