### PR TITLE
[SG-419] Added logging to mobile push notifications

### PR DESCRIPTION
**Pull request by trmartin4**
## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Code changes
[src/Core/Services/Implementations/BaseIdentityClientService.cs](https://github.com/bitwarden/server/pull/2332/files#diff-f40bc38440c349b3b3dc6ec0242c8d9b367ea47c5b1ccb172dc827ba06e2b741): Added logging when a token request fails.
[src/Core/Services/Implementations/MultiServicePushNotificationService.cs](https://github.com/bitwarden/server/compare/master...feat/passwordless-push-notification-logging#diff-f8d0c6ddc3626f1cc981881004ceb0cf09c17419521c91fdb8899fcc2779cfa3): Passed `hubLogger` in to `NotificationHubPushNotificationService` constructor.
[src/Core/Services/Implementations/NotificationHubPushNotificationService.cs](https://github.com/bitwarden/server/compare/master...feat/passwordless-push-notification-logging#diff-745e85ca3e13e36c3245db9518b44dd94b41426e2161b891569dcc648f0d569e): Added code to log the result of the `SendTemplateNotificationAsync()` call to the Notification Hub.  Introduced a `globalSettings` flag to enable or disable this logging.
[src/Core/Settings/GlobalSettings.cs](https://github.com/bitwarden/server/compare/master...feat/passwordless-push-notification-logging#diff-5db3f085aa29787450e768b1180caec9666b5dc485e5551d50bbb6cf882a6db7): Added new setting to `globalSettings` to control Notification Hub logging.  Note that this is independent of any definition of minimum log levels.
[test/Core.Test/Services/NotificationHubPushNotificationServiceTests.cs](https://github.com/bitwarden/server/compare/master...feat/passwordless-push-notification-logging#diff-0d379b9320c3e6d8ad7d5b3e64f0e37e664f69af3b408c065cd246826a6f8d7a): Added logger to tests.

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by trmartin4** [comment]
I'd like feedback on whether adding an `EnableLogging` flag on the `NotificationHub` settings object is confusing in the context of also having `LogLevelSettings` as another property on `GlobalSettings`. 

The distinction is that `LogLevelSettings` define the minimum logging level for each part of the application (i.e. what Serilog will actually log), whereas this specifics whether any logging at all is enabled for the Notification Hub logging, regardless of level.

**Comment by differsthecat** [comment]
> I'd like feedback on whether adding an `EnableLogging` flag on the `NotificationHub` settings object is confusing in the context of also having `LogLevelSettings` as another property on `GlobalSettings`.
> 
> The distinction is that `LogLevelSettings` define the minimum logging level for each part of the application (i.e. what Serilog will actually log), whereas this specifics whether any logging at all is enabled for the Notification Hub logging, regardless of level.

Can this be cleared up if the property is given a slightly different name, maybe `EnableLoggingOverride` to indicate that this is separate from `LogLevelSettings`?

**Comment by trmartin4** [comment]
@differsthecat I updated the name of the property to `EnableSendTracing`.  I did some more reading on what this actually does, when we tell the Azure Notification Hub to provide a more thorough response.  Without this flag set, every response is "Enqueued", meaning that the Azure Notification Hub received the message, but there is no indication of whether the message was successfully delivered to any platform notification service or to any device.

By setting the `EnableTestSend` property to true (which would happen if `EnableSendTracing`==true), we are telling the Azure Notification Hub to wait for the message to actually get sent to the device and provide the full result back (including any errors that occurred.  The documentation [here](https://learn.microsoft.com/en-us/azure/notification-hubs/notification-hubs-push-notification-fixer#net-sdk-example) is very clear that this should _only_ be used in a test environment, as it is throttled to only 10 requests a minute and only 10 devices.

I tried to make it clear in the comments that this is much more involved than just adjusting the logging level.

**Comment by differsthecat** [comment]
> @differsthecat I updated the name of the property to `EnableSendTracing`. I did some more reading on what this actually does, when we tell the Azure Notification Hub to provide a more thorough response. Without this flag set, every response is "Enqueued", meaning that the Azure Notification Hub received the message, but there is no indication of whether the message was successfully delivered to any platform notification service or to any device.
> 
> By setting the `EnableTestSend` property to true (which would happen if `EnableSendTracing`==true), we are telling the Azure Notification Hub to wait for the message to actually get sent to the device and provide the full result back (including any errors that occurred. The documentation [here](https://learn.microsoft.com/en-us/azure/notification-hubs/notification-hubs-push-notification-fixer#net-sdk-example) is very clear that this should _only_ be used in a test environment, as it is throttled to only 10 requests a minute and only 10 devices.
> 
> I tried to make it clear in the comments that this is much more involved than just adjusting the logging level.

Thanks @trmartin4 , that makes a lot of sense and I like the naming update you did to reflect what this property is better.  My understanding now is that this is a setting that will remain false for prod, but we will enable in test environments to get logs of these actions for us to debug before a release.

**Review by differsthecat — APPROVED** [review]
Looks good
Thank you @trmartin4 for your explanation on this!

**Pull request merged**
