### PR TITLE
add wasm-unsafe-eval to CSP

### PR DESCRIPTION
**Pull request by kspearrin**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Web vault CSP needs to be adjusted to support WASM for argon2.

cc @bitwarden/dept-cloudops @bitwarden/dept-devops 

## Code changes

* **nginx-config.hbs:** Add `wasm-unsafe-eval` to `script-src`.
* **Configuration.cs:** Add `wasm-unsafe-eval` to `script-src` and format line a bit better.

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by trmartin4** [comment]
Will this also require changes to the proxies in https://github.com/bitwarden/misc/tree/master/AzureFunctions?

**Comment by kspearrin** [comment]
> Will this also require changes to the proxies in https://github.com/bitwarden/misc/tree/master/AzureFunctions?

Yes, here: https://github.com/bitwarden/misc/pull/149

**Comment by trmartin4** [comment]
> > Will this also require changes to the proxies in https://github.com/bitwarden/misc/tree/master/AzureFunctions?
> 
> Yes, here: [bitwarden/misc#149](https://github.com/bitwarden/misc/pull/149)

Thank you.  I only looked for open PRs and missed that one.

**Review by MGibson1 — APPROVED** [review]
We'll need tickets for our prod and qa CSPs as well

**Pull request merged**
