### PR TITLE
[PM-10394] Add new item type ssh key

### PR DESCRIPTION
**Pull request by quexten**
## 🎟️ Tracking

Server: https://github.com/bitwarden/server/pull/4575
Add Item Type: https://github.com/bitwarden/clients/pull/10360
Add SSH Agent: https://github.com/bitwarden/clients/pull/10293
Add Import/Export: https://github.com/bitwarden/clients/pull/10529

Jira: https://bitwarden.atlassian.net/browse/PM-10395

## 📔 Objective

Add server support for the new ssh key cipher type. This is mostly copy paste from the other cipher types, with the one exception that we are filtering out ssh keys for older clients, using SSHKeyCipherMinimumVersion. We will update this once we know which release ssh keys will be in.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Comment by rawkode** [comment]
Very excited by this! Preparing to ditch 1Password as I type 🙂

**Comment by quexten** [comment]
Setting this to ready for review, but it will not be merged until all ssh of the ssh key features are ready.

**Review by gbubemismith — DISMISSED** [review]

**Review by gbubemismith — APPROVED** [review]

**Comment by quexten** [comment]
@justspacedog Could you please note: Your desktop version, your iOS version, and are you using a self-hosted server (if so which one at what version).

**Comment by justspacedog** [comment]
macOS: 2024.12.1
iOS: Version: 2024.12.0 (1740)
server: selfhosted vaultwarden latest (I know not official) as docker on a synology

**Comment by quexten** [comment]
@justspacedog Might be related to this PR in vaultwarden: https://github.com/dani-garcia/vaultwarden/pull/5339

**Comment by stabbach-santex** [comment]
:rocket: :rocket: :rocket:

**Comment by cksapp** [comment]
@quexten don't mean to necro-bump this PR, but I wanted to be sure _where_ the reported issue should be considered under the "client" repos, or likely this "server" repo as I would imagine there is something specific which would be required on the SSH Key item type in the server code.

---

Currently I see that SSH Key item types hold password history like all other vault items, similarly **Hidden** type custom fields are included in the item's **Password history**


Though what I would imagine should be considered another "important secret" would be the private key as an _**integral**_ portion of the SSH key pair. I understand there has been a [specific discussion](https://github.com/bitwarden/clients/pull/12176#issuecomment-2514596595) based around removing the option to regenerate the private key for these items exception upon initial creation.
> Removed the "regenerate" button, after this came up as a potential confusing point in a meeting. So ssh keys are now only generated when creating a new item.

So while there is little chance of editing over the existing private key, and consistent backups to an external location are highly critical for end user to perform, the Desktop application _does_ currently provide the ability for an SSH Key type to be overwritten on edit using the **Import key from clipboard** method.


Which is **not** currently captured in the item's **Password history**



So I suppose this could be handled in likely one of the following methods,
1. Either the **SSH Key** item type can support password history for **Private key** field, similarly to **Login** type supports in **Password** field
2. Easy workaround can be simply disable **Import key from clipboard** option in Desktop app on Editing vault item and only allow on initial creation

**Comment by mlec1** [comment]
> @justspacedog Might be related to this PR in vaultwarden: [dani-garcia/vaultwarden#5339](https://github.com/dani-garcia/vaultwarden/pull/5339)

I guess the best place for this kind of feedback, would be to post a comment on the community forum https://community.bitwarden.com/latest

**Comment by mlec1** [comment]
@cksapp I guess the best place for this kind of feedback would be to post a comment on the community forum https://community.bitwarden.com/latest

**Pull request merged**
