### PR TITLE
[Bug] Updated incorrect formatting/spelling on migrator script

### PR DESCRIPTION
**Pull request by vincentsalucci**
## Code Changes
- **2021-02-26_00_EmergencyAccess_ReadToNotify.sql**: Changed underscores to hyphens where necessary.  Changed `Acess` -> `Access`

### CODE REVIEW

**Comment by Hinton** [comment]
@vincentsalucci I could be mistaken but aren't filenames used as the unique key used to detect if the migration has been applied? I.e. renaming it would cause it to appear as a new migration which we re-apply. Which I guess might be fine since I don't see any more recent migration which affects this procedure.

**Comment by cscharf** [comment]
I would prefer we let this file name as-is and something as a team we can look out for these types of typos in the future for migration scripts.

**Comment by vincentsalucci** [comment]
> @vincentsalucci I could be mistaken but aren't filenames used as the unique key used to detect if the migration has been applied? I.e. renaming it would cause it to appear as a new migration which we re-apply. Which I guess might be fine since I don't see any more recent migration which affects this procedure.

I'm not 100% - luckily this appears to just be a sproc creation that has no downstream changes yet. Would rather clean it up ASAP to keep our patterns clean. Does this create and issues?

**Comment by mportune-bw** [comment]
> @vincentsalucci I could be mistaken but aren't filenames used as the unique key used to detect if the migration has been applied? I.e. renaming it would cause it to appear as a new migration which we re-apply. Which I guess might be fine since I don't see any more recent migration which affects this procedure.

I thought the check was performed within the script itself and the filenames are just for sorting.

**Comment by vincentsalucci** [comment]
> I would prefer we let this file name as-is and something as a team we can look out for these types of typos in the future for migration scripts.

I'm not sure we can leave it as-is. That would cause every other migrator script in the future to have to use the incorrect formatting to keep them in the (partially) correct order. Or if we use the original format (but leave this file as-is), any changes to the sproc `...ReadToNotify` will have to use the incorrect formatting to keep the desired order. Right?

**Comment by cscharf** [comment]
That's fair.... the script name **is** the key used to determine if a script has already been ran, but since it's only a sproc we can rename this one correctly.

see: https://dbup.readthedocs.io/en/latest/more-info/journaling/

**Review by cscharf — APPROVED** [review]

**Pull request merged**
