### PR TITLE
fix for #705 - added error handling and sha256 checksum validation

### PR DESCRIPTION
**Pull request by davidwinterstein**
Not sure if this commit & pull request match your requirements. Feel free to name any faults or missing information.

Commit is a rewrite of the `downloadSelf` function implementing error handling and checksum validation of the downloaded file.

### CODE REVIEW

**Comment by kspearrin** [comment]
I am a little confused about how this resolves the issue. It appears that you are just downloading the file twice and comparing the hashes. What if the file downloads as an error both times? Am I missing something?

**Comment by davidwinterstein** [comment]
`curl -fso $TMP_FILE $GITHUB_BASE_URL/scripts/bitwarden.sh` would usually either result in an empty or not existing file or a non-zero exit code in case of an error:

>     -f, --fail
>         (HTTP) Fail silently (no output at all) on server errors. This is mostly done
>         to  better  enable scripts etc to better deal with failed attempts. In normal
>         cases when an HTTP server fails to deliver a document,  it  returns  an  HTML
>         document stating so (which often also describes why and more). This flag will
>         prevent curl from outputting that and return error 22.
> 
>         This method is not fail-safe and there  are  occasions  where  non-successful
>         response  codes will slip through, especially when authentication is involved
>         (response codes 401 and 407).

`curl -fsSo- $GITHUB_BASE_URL/scripts/bitwarden.sh 2>&1` would generate a curl error message if an error occurred and redirect that to `stdout` so it would be contained in the checksummed input to `sha256sum`:

>     -S, --show-error
>         When used with -s, --silent, it makes curl show an error message if it fails.

That way, a successful download will evaluate as fine (since no error is added), while the checksum containing the curl error would differ from the checksum without it.

Also, the exit code of executed commands is generally checked.

It would obviously be a far better solution to provide the checksum in a separate file - preferrably not hosted on the same infrastructure - and use that for validation. That would require some work on the deployment chain, though, so it might be more of a long-term proposal while the changes in this pull request would quickly prevent deployment of invalid files.

**Comment by davidwinterstein** [comment]
Oh well, I just realized that you `set -e` at the beginning of the script, so the whole `if`-`then`-stuff could be removed for the commands that don't require cleanup in case of failure.

**Comment by kspearrin** [comment]
Could a more simple fix be to just test the contents of the first line of the file to see if they match what is expceted?

```
#!/usr/bin/env bash
```

If not, you know you got a bad file due to GitHub issues.

**Comment by davidwinterstein** [comment]
Yes, that would be a lot simpler and sufficient for handling the specific scenario in #705.

It's more of a quick-and-dirty fix in my opinion, though, since it does not account for situations like a partly downloaded file because of an aborted transfer for instance.\
My approach tries to address a variety of possible problems that might occur on the update of bitwarden.sh and would leave a defective environment control.

Also I think for security reasons checksum validation is a good idea in general, after all this is the control file for a password management server and my function could be easily improved to use a provided file with the actually expected checksum by changing
```
local SHA256SUM="$(curl -fsSo- $GITHUB_BASE_URL/scripts/bitwarden.sh 2>&1 |sha256sum - |awk '{print $1}')
```
to
```
local SHA256SUM="$(curl -fsSo- $SHA256URL 2>&1)"
```
in the future.

A valid objection might be that if an attacker was able to spoof the `bitwarden.sh` he would most probably also be able to spoof the checksum file since he would usually achieve that by manipulating DNS or similar. It would add a bit of effort, though. 😅
Maybe implementation of an optional switch like `--manually-validate-checksum` that reads user input from `stdin` and checks the file against that would be an option, although that would obviously deliberately disable automation of the update task, which would probably massively increase the time span from publication of an update to deployment at most users' setups - which would also be a security problem.

(Out of sheer curiosity: Are there statistics about the average elapsed time from publishment of an update to deployment at 90% of setups or so?)

**Pull request closed without merging**
