### PR TITLE
[PM-1959] Add Global equivalent domains for Internet Archive

### PR DESCRIPTION
**Pull request by TheBestPessimist**
## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add <kbd>Domain Rules</kbd> / <kbd>Global equivalent domains</kbd> for Internet Archive:
- `archive.org`
- `openlibrary.org`

## Code changes

_This should not be needed._

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required) ✅ 
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by dbosompem** [comment]
Hi @TheBestPessimist , after internal discussions, we decided not to go forward in merging this PR. It poses a security risk for us for now as we do not know if the site(s) are safe, and we would need to validate these and all other global domains submitted, which might take up some internal capacity.  We are currently looking into ways to take this burden off the community as we look to keep these domains up-to date.  You can add the custom equivalent domains personally, as outlined [here](https://bitwarden.com/help/uri-match-detection/#equivalent-domains) .This PR will now be closed.

**Comment by TheBestPessimist** [comment]
@dbosompem i cannot understand your rationale and i'm rather disappointed in this decision.

> It poses a security risk [...] do not know if the site(s) are safe

What exactly do you need to check for Internet Archive and Open Library, to have reassurance that they're the legit sites?

From a simple 1 google search you can see that Open Library belongs under the Internet Archive umbrella: https://github.com/internetarchive/openlibrary.

Please further expand on what are your reasons for the "security risk".

**Comment by TheBestPessimist** [comment]
On the same train of thought, how did you come to the "no longer a security risk" conclusion that `trello.com` and `statuspage.io` belong under the `atlassian` umbrella?

**Comment by TheBestPessimist** [comment]
@dbosompem reminder

**Comment by TheBestPessimist** [comment]
reminder again @dbosompem

**Pull request closed without merging**
