### PR TITLE
fix build-docker typo

### PR DESCRIPTION
**Pull request by Heshmatkhah**
## Type of change
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
The docker-build script has some typo and syntax errors

## Code changes

* **scripts/docker-build:** fix typo and syntax errors
## Testing requirements

No

## Before you submit
- [ ] If making database changes - I have also updated Entity Framework queries and/or migrations
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Comment by Hinton** [comment]
@joseph-flinn Do you know if this change will have any unforseen side effects?

**Comment by Hinton** [comment]
@Heshmatkhah Thanks for the PR, could you ensure the email address you commited using is added to your profile so that the CLAassistant can accept the commit?

**Comment by joseph-flinn** [comment]
@Hinton Nope. As far as I know, I might be the only one using that. I created it to start consolidating the `build.sh` scripts in each of the projects. We do not use it in the CI pipeline.

**Review by joseph-flinn — APPROVED** [review]

**Comment by Hinton** [comment]
@Heshmatkhah gentle ping that we need the CLA signed before we can merge this.

**Review by Hinton — CHANGES_REQUESTED** [review]
Need CLA signed.

**Comment by Heshmatkhah** [comment]
Hi,
I apologize for my delay.
I fixed my email address and signed the CLA.

**Review by Hinton — APPROVED** [review]

**Comment by Hinton** [comment]
@Heshmatkhah much appreciated. @joseph-flinn feel free to merge whenever you wish.

**Comment by joseph-flinn** [comment]
@Heshmatkhah Thanks for your contribution!

**Pull request merged**
