### PR TITLE
Fix possible syntax error

### PR DESCRIPTION
**Pull request by Barben360**
## Type of change
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Fixing syntax error in `run.sh` of https://github.com/bitwarden/server/issues/1801

## Code changes

Escape variable in a string to avoid syntax error in string comparison when variable undefined.

* **scripts/run.sh** Escape variable in a string to avoid syntax error in string comparison when variable undefined.

## Testing requirements

Update bitwarden using Docker method with provided `bitwarden.sh` script.

## Before you submit
- [x] I have checked for formatting errors (`dotnet tool run dotnet-format --check`) (required)
- [ ] ~~If making database changes - I have also updated Entity Framework queries and/or migrations~~
- [ ] ~~I have added **unit tests** where it makes sense to do so (encouraged but not required)~~
- [ ] ~~This change requires a **documentation update** (notify the documentation team)~~
- [ ] ~~This change has particular **deployment requirements** (notify the DevOps team)~~

### CODE REVIEW

**Comment by Barben360** [comment]
Hi, just did it. I don't know why it had not worked last time.

**Comment by djsmith85** [comment]
@Barben360  Did you maybe use a different email for the commit. One that is not associated with your Github account? There's a link at the bottom of the CLA message https://github.com/bitwarden/server/pull/1802#issuecomment-1008580383 where you can add a missing email.

**Comment by Barben360** [comment]
Indeed, I had pushed with the wrong git profile. I forced pushed with the right user.

**Review by mimartin12 — APPROVED** [review]
Good catch @Barben360. Thanks!

**Pull request merged**
