### PR TITLE
Improve EF Migration Workflow by Starting Required Docker Services Automatically

### PR DESCRIPTION
**Pull request by gbubemismith**
## Type of change

```
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

This pull request aims to simplify the EF migration process by updating the powershell script to automatically start the docker services for MySQL and Postgres before running the migration command.

## Code changes

* **dev/ef_migrate.ps1:** Get the container id for each service and check the status; if the status is not `running`, it attempts to start the service.

## Before you submit

- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Review by Hinton — COMMENTED** [review]
I believe you can just run `docker-compose --profile mysql up  -d --no-recreate`. Which should only start it if it's not already running.

We also only need mysql since it's doing version check (and we could probably just specify the version in the migrator util)

**Comment by gbubemismith** [comment]
> I believe you can just run `docker-compose --profile mysql up -d --no-recreate`. Which should only start it if it's not already running.
> 
> We also only need mysql since it's doing a version check (and we could probably just specify the version in the migrator util)

Thanks, Oscar. That would reduce the lines significantly.  So are you saying this is not needed for `postgres`?

**Comment by Hinton** [comment]
Yes, we don't need postgres running when generating ef migrations.

**Review by Hinton — APPROVED** [review]

**Review by justindbaur — CHANGES_REQUESTED** [review]
Maybe I'm wrong but I didn't think the `migrations add` command needs the database to be running at all. [It doesn't even have an option to pass in the connection string](https://learn.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-migrations-add). I thought it creates the migrations through static analysis and only needs the database to apply the migration onto the database and in that case this would make more sense in `migrate.ps1`.

**Comment by Hinton** [comment]
@justindbaur https://github.com/bitwarden/server/blob/master/util/MySqlMigrations/Factories.cs#L39

**Comment by justindbaur** [comment]
@Hinton Oh yeah... disregard, that really scares me that depending on the developers MySql version it could create a different migration.

**Review by justindbaur — APPROVED** [review]

**Pull request merged**
